# Generated by Django 5.0.9 on 2024-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSufficiency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategyCategory", models.CharField(max_length=255)),
                (
                    "strategyCategory_de",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "strategyCategory_en",
                    models.CharField(max_length=255, null=True),
                ),
                ("categoryShortDescription", models.TextField()),
                ("categoryShortDescription_de", models.TextField(null=True)),
                ("categoryShortDescription_en", models.TextField(null=True)),
                ("categoryLongDescription", models.TextField()),
                ("categoryLongDescription_de", models.TextField(null=True)),
                ("categoryLongDescription_en", models.TextField(null=True)),
                ("example1", models.TextField(blank=True, null=True)),
                ("example1_de", models.TextField(blank=True, null=True)),
                ("example1_en", models.TextField(blank=True, null=True)),
                (
                    "example1Heading",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "example1Heading_de",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "example1Heading_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("example2", models.TextField(blank=True, null=True)),
                ("example2_de", models.TextField(blank=True, null=True)),
                ("example2_en", models.TextField(blank=True, null=True)),
                (
                    "example2Heading",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "example2Heading_de",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "example2Heading_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "literature",
                    models.ManyToManyField(
                        blank=True, null=True, to="common.literature"
                    ),
                ),
            ],
        ),
    ]
