# Generated by Django 4.2.1 on 2024-08-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0001_initial'),
        ('data_sufficiency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasufficiency',
            name='example1Heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='datasufficiency',
            name='literature',
            field=models.ManyToManyField(blank=True, null=True, to='user_integration.literature'),
        ),
    ]
