# Generated by Django 4.2.1 on 2024-09-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data_sufficiency", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasufficiency",
            name="example1Heading_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="datasufficiency",
            name="example1Heading_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="datasufficiency",
            name="example2Heading_de",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="datasufficiency",
            name="example2Heading_en",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
