# Generated by Django 4.2.1 on 2024-08-09 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sufficiency', '0002_datasufficiency_example1heading_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasufficiency',
            name='example2Heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
