# Generated by Django 4.2.1 on 2024-08-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sufficiency', '0003_datasufficiency_example2heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasufficiency',
            name='example1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasufficiency',
            name='example1_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasufficiency',
            name='example1_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasufficiency',
            name='example2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasufficiency',
            name='example2_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datasufficiency',
            name='example2_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
