# Generated by Django 4.2.1 on 2024-09-02 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "project_listing",
            "0002_remove_subproject_questionnaire2021_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enargus",
            name="rAndDPlanningCategory",
            field=models.ForeignKey(
                blank=True,
                help_text="number of the systematic performance plan ('leistungsplan\n            systematik')",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="project_listing.randdplanningcategory",
            ),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="priority1",
            field=models.CharField(
                blank=True,
                help_text="Project allocation with priority 1 (main contact partner)\n            e.g. M2, M1, ag: ausgelaufen",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="priority2",
            field=models.CharField(
                blank=True,
                help_text="Project allocation with priority 2 (main contact partner)\n            e.g. M2, M1, ag: ausgelaufen",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="priority3",
            field=models.CharField(
                blank=True,
                help_text="Project allocation with priority 3 (main contact partner)\n            e.g. M2, M1, ag: ausgelaufen",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="moduleassignment",
            name="priority4",
            field=models.CharField(
                blank=True,
                help_text="Project allocation with priority 4 (main contact partner)\n            e.g. M2, M1, ag: ausgelaufen",
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="randdplanningcategory",
            name="rAndDPlanningCategoryNumber",
            field=models.CharField(
                help_text="identifier number of the performance plan systematic -\n            'Leistungsplansystematiknummer'",
                max_length=6,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="subproject",
            name="referenceNumber_id",
            field=models.CharField(
                help_text="Funding code (numerical sequence of 9 to 10 characters),\n            fkz - Förderkennzeichen",
                max_length=10,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
