# Generated by Django 4.2.1 on 2024-07-17 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0002_tools_name_de_tools_name_en"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tools",
            name="name_de",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="name_en",
        ),
    ]
