# Generated by Django 5.0.9 on 2024-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0003_remove_tools_name_de_remove_tools_name_en"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
            ],
        ),
    ]
