# Generated by Django 5.0.9 on 2024-11-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0003_remove_tools_name_de_remove_tools_name_en"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tools",
            name="applicationArea",
            field=models.ManyToManyField(
                db_comment="What do the developers describe as the area of application of their digital tool",
                to="tools_over.applicationarea",
            ),
        ),
    ]
