# Generated by Django 5.0.9 on 2024-10-27 06:43

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0004_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="history",
            name="updateDate",
            field=models.DateTimeField(
                db_default=django.db.models.functions.datetime.Now()
            ),
        ),
    ]
