# Generated by Django 5.0.9 on 2024-11-12 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0004_alter_tools_applicationarea"),
        ("tools_over", "0005_history_updatedate"),
    ]

    operations = []
