# Generated by Django 5.0.9 on 2024-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0006_merge_20241112_0916"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tools",
            name="programmingLanguages",
            field=models.CharField(
                blank=True,
                db_comment="Programming languages - Which programming languages are mainly used to implment the item.",
                max_length=500,
            ),
        ),
    ]
