# Generated by Django 5.0.9 on 2024-11-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0002_remove_protocol_associatedtools"),
        ("tools_over", "0007_alter_tools_programminglanguages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tools",
            name="technicalStandardsProtocols",
            field=models.ManyToManyField(
                blank=True, null=True, to="protocols.protocol"
            ),
        ),
    ]
