# Generated by Django 5.0.9 on 2024-11-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_license_licensingfeerequirement_de_and_more"),
        ("tools_over", "0008_alter_tools_technicalstandardsprotocols"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tools",
            name="license",
        ),
        migrations.AddField(
            model_name="tools",
            name="license",
            field=models.ManyToManyField(to="common.license"),
        ),
    ]
