# Generated by Django 5.0.9 on 2024-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_license_licensingfeerequirement_de_and_more"),
        (
            "project_listing",
            "0003_alter_enargus_randdplanningcategory_and_more",
        ),
        ("tools_over", "0009_remove_tools_license_tools_license"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tools",
            name="shortDescription",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="shortDescription_de",
        ),
        migrations.RemoveField(
            model_name="tools",
            name="shortDescription_en",
        ),
        migrations.AddField(
            model_name="tools",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="accessibility",
            field=models.ManyToManyField(
                db_comment="Accessibility - How accessible is the dataset?",
                to="tools_over.accessibility",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="alternatives",
            field=models.CharField(
                blank=True,
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of dataset - Which type or of to which typ belongs the dataset. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="developmentState",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "pre-alpha"),
                    (2, "alpha"),
                    (3, "beta"),
                    (4, "release candidate"),
                    (5, "release"),
                ],
                db_comment="Level of development - What is the curent development status",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="focus",
            field=models.ManyToManyField(
                db_comment="Focus identifier - Selected focus (Definied by Wissensplattform)",
                max_length=200,
                to="tools_over.focus",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="furtherInformation",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="furtherInformation_de",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="furtherInformation_en",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="image",
            field=models.ImageField(
                blank=True,
                db_comment="File name of image file. Located in media-folder.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="license",
            field=models.ManyToManyField(
                db_comment="under which license was the item published and are there any costs associated with using the dataset?",
                to="common.license",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="lifeCyclePhase",
            field=models.ManyToManyField(
                db_comment="Life cycle phase - In which phase of the product life cycle is the tool used?",
                to="tools_over.lifecyclephase",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="name",
            field=models.CharField(
                db_comment="Name of the item", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="programmingLanguages",
            field=models.CharField(
                blank=True,
                db_comment="Programming languages - Which programming languages are mainly used to implment the item.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="provider",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="provider_de",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="provider_en",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="released",
            field=models.BooleanField(
                blank=True,
                db_comment="Released - Is the publication done?",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="resources",
            field=models.CharField(
                blank=True,
                db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="scale",
            field=models.ManyToManyField(
                db_comment="Spatial scale of the use cases - On what scale is the dataset used?",
                to="tools_over.scale",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="specificApplication",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Specific use cases - Identification of concrete examples of the use of the item in the construction sector/energy transition (equals project number)",
                to="project_listing.subproject",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="targetGroup",
            field=models.ManyToManyField(
                db_comment="Target group - Who do you say the digital item is aimed at?",
                to="tools_over.targetgroup",
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="yearOfRelease",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="yearOfRelease_de",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tools",
            name="yearOfRelease_en",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
    ]
