# Generated by Django 5.0.9 on 2024-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools_over", "0010_remove_tools_shortdescription_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tools",
            name="description_de",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tools",
            name="description_en",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
    ]
