# Generated by Django 4.2.1 on 2024-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.CharField(blank=True, max_length=255, null=True)),
                ('challenge_de', models.CharField(blank=True, max_length=255, null=True)),
                ('challenge_en', models.CharField(blank=True, max_length=255, null=True)),
                ('shortDescription', models.TextField(blank=True, null=True)),
                ('shortDescription_de', models.TextField(blank=True, null=True)),
                ('shortDescription_en', models.TextField(blank=True, null=True)),
                ('property1', models.CharField(blank=True, max_length=255, null=True)),
                ('property1_de', models.CharField(blank=True, max_length=255, null=True)),
                ('property1_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property1Text', models.TextField(blank=True, null=True)),
                ('property1Text_de', models.TextField(blank=True, null=True)),
                ('property1Text_en', models.TextField(blank=True, null=True)),
                ('property2', models.CharField(blank=True, max_length=255, null=True)),
                ('property2_de', models.CharField(blank=True, max_length=255, null=True)),
                ('property2_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property2Text', models.TextField(blank=True, null=True)),
                ('property2Text_de', models.TextField(blank=True, null=True)),
                ('property2Text_en', models.TextField(blank=True, null=True)),
                ('property3', models.CharField(blank=True, max_length=255, null=True)),
                ('property3_de', models.CharField(blank=True, max_length=255, null=True)),
                ('property3_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property3Text', models.TextField(blank=True, null=True)),
                ('property3Text_de', models.TextField(blank=True, null=True)),
                ('property3Text_en', models.TextField(blank=True, null=True)),
                ('property4', models.CharField(blank=True, max_length=255, null=True)),
                ('property4_de', models.CharField(blank=True, max_length=255, null=True)),
                ('property4_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property4Text', models.TextField(blank=True, null=True)),
                ('property4Text_de', models.TextField(blank=True, null=True)),
                ('property4Text_en', models.TextField(blank=True, null=True)),
                ('property5', models.CharField(blank=True, max_length=255, null=True)),
                ('property5_de', models.CharField(blank=True, max_length=255, null=True)),
                ('property5_en', models.CharField(blank=True, max_length=255, null=True)),
                ('property5Text', models.TextField(blank=True, null=True)),
                ('property5Text_de', models.TextField(blank=True, null=True)),
                ('property5Text_en', models.TextField(blank=True, null=True)),
                ('imageIcon', models.CharField(blank=True, max_length=255, null=True)),
                ('imageIconSelected', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
