# Generated by Django 4.2.1 on 2024-05-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortDescription', models.CharField(max_length=255)),
                ('property1', models.CharField(max_length=255)),
                ('property1Text', models.TextField()),
                ('property2', models.CharField(max_length=255)),
                ('property2Text', models.TextField()),
                ('property3', models.CharField(max_length=255)),
                ('property3Text', models.TextField()),
                ('property4', models.CharField(max_length=255)),
                ('property4Text', models.TextField()),
                ('property5', models.CharField(max_length=255)),
                ('property5Text', models.TextField()),
            ],
        ),
    ]
