# Generated by Django 4.2.1 on 2024-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='challenge',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='shortDescription',
            field=models.TextField(),
        ),
    ]
