# Generated by Django 4.2.1 on 2024-05-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0003_businessmodel_imageicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessmodel',
            name='challenge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property1Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property2Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property3Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property4Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='property5Text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessmodel',
            name='shortDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
