# Generated by Django 4.2.1 on 2024-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0004_alter_businessmodel_challenge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodel',
            name='imageIconSelected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
