# Generated by Django 4.2.1 on 2024-05-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0005_businessmodel_imageiconselected'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryShortDescription', models.TextField(blank=True, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('subCategoryShortDescription', models.TextField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('timeRequired', models.CharField(blank=True, max_length=255, null=True)),
                ('groupSize', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('advantages', models.TextField(blank=True, null=True)),
                ('disadvantages', models.TextField(blank=True, null=True)),
                ('conductedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('successFactors', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('procedure', models.TextField(blank=True, null=True)),
                ('specificGoals', models.TextField(blank=True, null=True)),
                ('specificProcedure', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
