# Generated by Django 4.2.1 on 2024-05-28 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0006_userintegration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIntegration',
            new_name='UserEngagement',
        ),
    ]
