# Generated by Django 4.2.1 on 2024-05-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0007_rename_userintegration_userengagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='imageIcon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='imageIconSelected',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
