# Generated by Django 4.2.1 on 2024-05-29 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0008_userengagement_imageicon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureItem', models.CharField(blank=True, max_length=255, null=True)),
                ('userEngagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businessModel.userengagement')),
            ],
        ),
    ]
