# Generated by Django 4.2.1 on 2024-05-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0009_procedureitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificProcedureItem', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='procedureitem',
            name='userEngagement',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='specificProcedure',
        ),
        migrations.AddField(
            model_name='userengagement',
            name='procedure',
            field=models.ManyToManyField(blank=True, null=True, to='businessModel.procedureitem'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='specificProcedure',
            field=models.ManyToManyField(blank=True, null=True, to='businessModel.specificprocedureitem'),
        ),
    ]
