# Generated by Django 4.2.1 on 2024-05-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0010_specificprocedureitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userengagement',
            name='participantObservations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='persons',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
