# Generated by Django 4.2.1 on 2024-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "businessModel",
            "0011_userengagement_participantobservations_and_more",
        ),
    ]

    operations = []
