# Generated by Django 4.2.1 on 2024-07-01 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessModel', '0012_businessmodel_challenge_de_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='specificProcedure',
        ),
        migrations.DeleteModel(
            name='ProcedureItem',
        ),
        migrations.DeleteModel(
            name='SpecificProcedureItem',
        ),
        migrations.DeleteModel(
            name='UserEngagement',
        ),
    ]
