# Generated by Django 5.0.9 on 2024-12-13 18:26

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businessModel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
                (
                    "updateDate",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
