version: "3.9"
services:
    webcentral:
        build:
            context: ${PWD}
            dockerfile: Dockerfile
            target: dev
        command: >
            bash -c "python3 01_application/webcentral_app/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ${PWD}:/webcentral/
