services:
    webcentral:
        build:
            context: ${PWD}/webcentral/
            dockerfile: Dockerfile
            target: dev
        command: >
            bash -c "python3 src/manage.py runserver 0.0.0.0:8000"
        volumes:
            - ${PWD}/webcentral:/webcentral/
