version: "3.9"
services:
    webcentral:
        build:
            context: ${PATH_WEBCENTRAL_SRC}
            dockerfile: Dockerfile
            target: prod
            
        volumes:
            - static-data:/vol/webcentral
        depends_on:
            - database
        restart: always
        environment:
            - UWSGI_LISTEN_PORT
            - UWSGI_NUM_WORKERS
            - SECRET_KEY
            - DEBUG
            - ALLOWED_HOSTS
            - MODE=production
        command: >
            sh -c "sphinx-apidoc -f -o 02_work_doc/06_sphinx/source/ 01_application/webcentral_app/ data_import.py && \
            sphinx-build 02_work_doc/06_sphinx/source 01_application/webcentral_app/webcentral_app/static/ && \
            python /src/01_application/webcentral_app/manage.py collectstatic --noinput && \
            uwsgi --socket :${UWSGI_LISTEN_PORT} --chdir=/src/01_application/webcentral_app --master --processes 4 --threads 2 --module=webcentral_app.wsgi:application"


    proxy:
        container_name: proxy
        build:
            context: ./proxy
        restart: always
        depends_on:
            - webcentral
        ports:
            - ${PORT_TO_OUTSIDE}:${NGINX_LISTEN_PORT}
            - 443:443
            # data communication on port 80 on the host
            # gets mapped to port 8000 inside the proxy container
        environment:
            - NGINX_LISTEN_PORT
            - UWSGI_LISTEN_PORT
        volumes:
            - static-data:/vol/static
            - ./proxy/dhparam/:/etc/nginx/dhparam
            - ./proxy/conf/:/etc/nginx/ssl/
            # the proxy can directly serve the static data, without bothering
            # the django app
        command: >
            bash -c "if [[ "$USE_PROD_LOCALLY" == "0" ]]; then envsubst < /etc/nginx/default.conf.tpl > /etc/nginx/conf.d/default.conf; else envsubst < /etc/nginx/localDefault.conf.tpl > /etc/nginx/conf.d/default.conf; fi && \
            nginx -g 'daemon off;'"
volumes:
    static-data:
