version: "3.9"
services:
    webcentral:
        command: python 01_application/webcentral_app/manage.py runserver 0.0.0.0:8000
        volumes:
            - ${PWD}:/home/${WEBCENTRAL_UNPRIVILEGED_USER}
