# Generated by Django 4.0.3 on 2022-04-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('schlagwort_id', models.AutoField(help_text='Auto.generiert ID', primary_key=True, serialize=False)),
                ('schlagwort', models.CharField(blank=True, help_text='Name des Schlagworts', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Schlagwortregister_erstsichtung',
            fields=[
                ('schlagwortregister_erstsichtung_id', models.AutoField(help_text='Auto.generiert ID', primary_key=True, serialize=False)),
                ('schlagwort_1', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_2', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_3', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_4', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_5', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_6', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
                ('schlagwort_7', models.CharField(blank=True, help_text='Schlagwort, Erstsichtung der Projekte über die Kurzbeschreibung (Ende 2020)', max_length=50)),
            ],
        ),
    ]
