# Generated by Django 3.2.9 on 2022-07-14 09:57

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('schlagwort_id', models.AutoField(help_text='Auto.generiert ID', primary_key=True, serialize=False)),
                ('schlagwort', models.CharField(blank=True, help_text='Name des Schlagworts', max_length=200)),
                ('schlagwort_definiton', models.CharField(blank=True, help_text='Definition des Schlagworts', max_length=1500)),
                ('literatur', models.CharField(blank=True, help_text='Literaturquellen zum Schlagwort', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Schlagwortregister_erstsichtung',
            fields=[
                ('schlagwortregister_id', models.AutoField(help_text='Auto.generiert ID', primary_key=True, serialize=False)),
                ('schlagwort_1', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_1', to='schlagwoerter.schlagwort')),
                ('schlagwort_2', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_2', to='schlagwoerter.schlagwort')),
                ('schlagwort_3', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_3', to='schlagwoerter.schlagwort')),
                ('schlagwort_4', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_4', to='schlagwoerter.schlagwort')),
                ('schlagwort_5', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_5', to='schlagwoerter.schlagwort')),
                ('schlagwort_6', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_6', to='schlagwoerter.schlagwort')),
                ('schlagwort_7', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_7', to='schlagwoerter.schlagwort')),
            ],
        ),
    ]
