# Generated by Django 4.0.3 on 2022-04-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schlagwoerter', '0002_alter_schlagwortregister_erstsichtung_schlagwort_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schlagwort',
            name='literatur',
            field=models.CharField(blank=True, help_text='Literaturquellen zum Schlagwort', max_length=1500),
        ),
        migrations.AddField(
            model_name='schlagwort',
            name='schlagwort_definiton',
            field=models.CharField(blank=True, help_text='Definition des Schlagworts', max_length=1500),
        ),
    ]
