# Generated by Django 3.2.13 on 2022-05-03 11:09

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('schlagwoerter', '0003_schlagwort_literatur_schlagwort_schlagwort_definiton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_1',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_1', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_2',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_2', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_3',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_3', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_4',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_4', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_5',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_5', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_6',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_6', to='schlagwoerter.schlagwort'),
        ),
        migrations.AlterField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_7',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_7', to='schlagwoerter.schlagwort'),
        ),
    ]
