# Generated by Django 3.2.13 on 2022-05-03 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schlagwoerter', '0004_auto_20220503_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schlagwortregister_erstsichtung',
            old_name='schlagwortregister_erstsichtung_id',
            new_name='schlagwortregister_id',
        ),
    ]
