# Generated by Django 5.0.9 on 2024-12-10 11:41

import publications.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("file", models.FileField(upload_to="publications/")),
            ],
        ),
        migrations.CreateModel(
            name="CustomLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=256)),
                ("url", models.URLField(verbose_name="URL")),
            ],
        ),
        migrations.CreateModel(
            name="List",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("list", models.CharField(max_length=128)),
                ("description", models.CharField(max_length=128)),
            ],
            options={
                "verbose_name_plural": "Lists",
                "ordering": ("list",),
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "citekey",
                    models.CharField(
                        blank=True,
                        help_text="BibTex citation key. Leave blank if unsure.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("title_de", models.CharField(max_length=512, null=True)),
                ("title_en", models.CharField(max_length=512, null=True)),
                (
                    "authors",
                    models.CharField(
                        help_text="List of authors separated by commas or <i>and</i>.",
                        max_length=2048,
                    ),
                ),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "month",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ],
                        null=True,
                    ),
                ),
                ("journal", models.CharField(blank=True, max_length=256)),
                (
                    "journal_de",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "journal_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("book_title", models.CharField(blank=True, max_length=256)),
                ("publisher", models.CharField(blank=True, max_length=256)),
                ("institution", models.CharField(blank=True, max_length=256)),
                (
                    "institution_de",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "institution_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("volume", models.IntegerField(blank=True, null=True)),
                (
                    "number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Issue number"
                    ),
                ),
                (
                    "pages",
                    publications.fields.PagesField(blank=True, max_length=32),
                ),
                ("note", models.CharField(blank=True, max_length=256)),
                (
                    "keywords",
                    models.CharField(
                        blank=True,
                        help_text="List of keywords separated by commas.",
                        max_length=512,
                    ),
                ),
                (
                    "keywords_de",
                    models.CharField(
                        blank=True,
                        help_text="List of keywords separated by commas.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "keywords_en",
                    models.CharField(
                        blank=True,
                        help_text="List of keywords separated by commas.",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Link to PDF or journal page.",
                        verbose_name="URL",
                    ),
                ),
                (
                    "code",
                    models.URLField(
                        blank=True, help_text="Link to page with code."
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="publications/",
                        verbose_name="PDF",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="publications/images/"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="publications/thumbnails/",
                    ),
                ),
                (
                    "doi",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="DOI"
                    ),
                ),
                (
                    "external",
                    models.BooleanField(
                        default=False,
                        help_text="If publication was written in another lab, mark as external.",
                    ),
                ),
                ("abstract", models.TextField(blank=True)),
                ("abstract_de", models.TextField(blank=True, null=True)),
                ("abstract_en", models.TextField(blank=True, null=True)),
                (
                    "isbn",
                    models.CharField(
                        blank=True,
                        help_text="Only for a book.",
                        max_length=32,
                        verbose_name="ISBN",
                    ),
                ),
                ("copyright", models.CharField(blank=True, max_length=256)),
                (
                    "copyright_de",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "copyright_en",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "verbose_name_plural": " Publications",
                "ordering": ["-year", "-month", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(db_index=True, editable=False),
                ),
                ("type", models.CharField(max_length=128)),
                ("type_de", models.CharField(max_length=128, null=True)),
                ("type_en", models.CharField(max_length=128, null=True)),
                ("description", models.CharField(max_length=128)),
                ("description_de", models.CharField(max_length=128, null=True)),
                ("description_en", models.CharField(max_length=128, null=True)),
                (
                    "bibtex_types",
                    models.CharField(
                        default="article",
                        help_text="Possible BibTex types, separated by comma.",
                        max_length=256,
                        verbose_name="BibTex types",
                    ),
                ),
                (
                    "bibtex_types_de",
                    models.CharField(
                        default="article",
                        help_text="Possible BibTex types, separated by comma.",
                        max_length=256,
                        null=True,
                        verbose_name="BibTex types",
                    ),
                ),
                (
                    "bibtex_types_en",
                    models.CharField(
                        default="article",
                        help_text="Possible BibTex types, separated by comma.",
                        max_length=256,
                        null=True,
                        verbose_name="BibTex types",
                    ),
                ),
                (
                    "hidden",
                    models.BooleanField(
                        default=False,
                        help_text="Hide publications from main view.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "  Types",
                "ordering": ("order",),
            },
        ),
    ]
