# Generated by Django 3.2.18 on 2023-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isNorm', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, help_text='name of the norm', max_length=150)),
                ('title', models.CharField(blank=True, help_text='title of the norm', max_length=250)),
                ('shortDescription', models.TextField(help_text='short description', max_length=600)),
                ('source', models.CharField(blank=True, help_text='source', max_length=100)),
                ('link', models.CharField(blank=True, help_text='link', max_length=150)),
            ],
        ),
    ]
