# Generated by Django 3.2.9 on 2023-04-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms_over', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='Link',
            field=models.CharField(blank=True, help_text='Link zur Norm', max_length=1000),
        ),
    ]
