# Generated by Django 3.2.9 on 2023-04-17 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms_over', '0003_alter_norms_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='Link',
            field=models.TextField(blank=True, help_text='Link zur Norm', max_length=500),
        ),
        migrations.AlterField(
            model_name='norms',
            name='Name',
            field=models.CharField(blank=True, help_text='Name der Norm', max_length=250),
        ),
        migrations.AlterField(
            model_name='norms',
            name='ShortDescription',
            field=models.TextField(help_text='Kurzbeschreibung der Norm', max_length=5000),
        ),
        migrations.AlterField(
            model_name='norms',
            name='Source',
            field=models.TextField(blank=True, help_text='Quelle der Norm', max_length=500),
        ),
        migrations.AlterField(
            model_name='norms',
            name='Title',
            field=models.CharField(blank=True, help_text='Titel der Norm', max_length=255),
        ),
    ]
