# Generated by Django 3.2.9 on 2023-05-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms_over', '0004_auto_20230417_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='Name',
            field=models.TextField(blank=True, help_text='Name der Norm', max_length=300),
        ),
        migrations.AlterField(
            model_name='norms',
            name='ShortDescription',
            field=models.TextField(help_text='Kurzbeschreibung der Norm', max_length=500),
        ),
        migrations.AlterField(
            model_name='norms',
            name='Title',
            field=models.TextField(blank=True, help_text='Titel der Norm', max_length=255),
        ),
    ]
