# Generated by Django 3.2.9 on 2023-05-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms_over', '0005_auto_20230502_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalStandards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_norm', models.TextField(default=True)),
                ('name', models.TextField(blank=True, help_text='name of the norm', max_length=300)),
                ('shortDescription', models.TextField(help_text='short description', max_length=500)),
                ('title', models.TextField(blank=True, help_text='title of the norm', max_length=255)),
                ('source', models.TextField(blank=True, help_text='source', max_length=500)),
                ('link', models.TextField(blank=True, help_text='link', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Norms',
        ),
    ]
