# Generated by Django 3.2.9 on 2023-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms_over', '0006_auto_20230510_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalstandards',
            name='is_norm',
        ),
        migrations.AddField(
            model_name='technicalstandards',
            name='isNorm',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='technicalstandards',
            name='link',
            field=models.CharField(blank=True, help_text='link', max_length=150),
        ),
        migrations.AlterField(
            model_name='technicalstandards',
            name='name',
            field=models.CharField(blank=True, help_text='name of the norm', max_length=150),
        ),
        migrations.AlterField(
            model_name='technicalstandards',
            name='shortDescription',
            field=models.TextField(help_text='short description', max_length=600),
        ),
        migrations.AlterField(
            model_name='technicalstandards',
            name='source',
            field=models.CharField(blank=True, help_text='source', max_length=100),
        ),
        migrations.AlterField(
            model_name='technicalstandards',
            name='title',
            field=models.CharField(blank=True, help_text='title of the norm', max_length=250),
        ),
    ]
