name: "Protocols Data Contribution"
description: "Template for submitting data about protocols"
title: "[ContributionProtocol]: <title>"
labels: ["Protocol Contribution", "Contribution", "Data"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this data contribution questionnaire!

  - type: input
    id: protocol_name
    attributes:
      label: "1. Name of the Protocol"
      description: "Please provide the name of the protocol."
      placeholder: "e.g., BACnet"
    validations:
      required: true

  - type: dropdown
    id: transmission_media
    attributes:
      label: "2. Transmission Media"
      description: "How are data transmitted between the different components and devices within the system (wired, wireless, or both)?"
      options:
        - 'Unknown'
        - 'wired'
        - 'wireless'
        - 'wired & wireless'
      default: 0

  - type: input
    id: supported_transmission_media
    attributes:
      label: "3. Supported Transmission Media"
      description: "How are signals transmitted (e.g., Twisted pair, fiber optics, Wireless mesh)?"
      placeholder: "e.g., Fiber optics, ..."

  - type: textarea
    id: related_standards
    attributes:
      label: "4. Related Standards"
      description: "Specify the standards to which the protocol can be assigned (e.g., IEEE, ISO)."
      placeholder: "e.g., ISO-16484-6, ..."

  - type: checkboxes
    id: open_source_status
    attributes:
      label: "5. Open-Source Status"
      description: "Is the protocol public and freely available?"
      options:
        - label: "Open Source"
        - label: "Proprietary"

  - type: dropdown
    id: license_fee
    attributes:
      label: "6. License Fee"
      description: "Is there a fee for using the protocol or certification?"
      options:
        - unknown
        - Fee required
        - No fee required
      default: 0
      
  - type: input
    id: network_topology
    attributes:
      label: "7. Network Topology"
      description: "What is the physical and logical arrangement of devices in the network?"
      placeholder: "e.g., star, ..."

  - type: textarea
    id: implemented_security_mechanisms
    attributes:
      label: "8. Implemented Security Mechanisms"
      description: "What security mechanisms are implemented to ensure data security?"

  - type: input
    id: bandwidth
    attributes:
      label: "9. Bandwidth"
      description: "What is the communication channel capacity (bandwidth) for transmitting data between the various components of the system?"
      placeholder: "e.g., 100 Mbps"

  - type: input
    id: frequency
    attributes:
      label: "10. Frequency"
      description: "What frequency or wavelength is used for communication (in wireless systems)?"
      placeholder: "e.g., 2.4 GHz or Not applicable"

  - type: input
    id: range
    attributes:
      label: "11. Range"
      description: "the maximum distance over which communication can be maintained between the various devices and components of the system without the signal strength becoming too weak."
      placeholder: "e.g., 50 meters"

  - type: checkboxes
    id: implemented_osi_layer
    attributes:
      label: "12. Implemented OSI-layer"
      description: "Which OSI reference model layers are applied for communication between the various components of the system in the protocol? Multiple choices allowed."
      options: 
        - label: "Application layer"
        - label: "Presentation layer"
        - label: "Session layer"
        - label: "Transport layer"
        - label: "Network/Packet layer"
        - label: "Data Link layer"
        - label: "Physical layer"

  - type: checkboxes
    id: levels_of_building_automation
    attributes:
      label: "13. Levels of Building Automation"
      description: "Describe the hierarchical structure for building automation system where the protocol is applied. Multiple choices allowed."
      options: 
        - label: "Field level"
        - label: "Automation level"
        - label: "Management level"

  - type: input
    id: data_model_architecture
    attributes:
      label: "14. Data Model Architecture"
      description: "How is information or attributes added to an object in the system?"

  - type: dropdown
    id: discovery
    attributes:
      label: "15. Discovery"
      description: "Does the protocol has the “discovery” function to automatically identify devices during data transfer?"
      options:
        - 'Unknown'
        - 'Yes'
        - 'No'
      default: 0

  - type: dropdown
    id: multi_master
    attributes:
      label: "16. Multi Master"
      description: "Can multiple master devices operate simultaneously?"
      options:
        - 'Unknown'
        - 'Yes'
        - 'No'
      default: 0

  - type: textarea
    id: priority
    attributes:
      label: "17. Priority"
      description: "How are changes or updates managed within the protocol (priority handling)?"
      placeholder: "e.g., Priority-based scheduling"

  - type: textarea
    id: typical_application
    attributes:
      label: "18. Typical Application"
      description: "If applicable, provide an example of how the protocol is used in a real-world scenario."
      placeholder: "e.g., Used in building management systems"

  - type: textarea
    id: link
    attributes:
      label: "19. Link"
      description: "Please provide a link for further information about the protocol."

  - type: textarea
    id: Suggestion
    attributes:
      label: "20. Suggestion about this questionnaire"
      description: "Please feel free to write any suggestion about this questionaire if be confused about questions."
      placeholder: "e.g., Do not understand the question of [], ..."

  - type: markdown
    attributes:
      value: |
        ## You have finished all the questions! Thank you for the data contribution!

  - type: markdown
    attributes:
      value: "**Note:** Please ensure that the data is correctly formatted before submission."
