name: "Protocols Data Contribution"
description: "Template for submitting data about protocols"
title: "[ContributionProtocol]: <title>"
labels: ["Protocol Contribution", "Contribution", "Data"]
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for taking the time to fill out this data contribution questionnaire!

  - type: input
    id: protocol_name
    attributes:
      label: "Name of the Protocol"
      description: "Please provide the name of the protocol."
      placeholder: "e.g., BACnet"

  - type: dropdown
    id: transmission_media
    attributes:
      label: "Transmission Media"
      description: "How are data transmitted between the different components and devices within the system (wired, wireless, or both)?"
      options:
        - wired
        - wireless
        - wired & wireless

  - type: input
    id: supported_transmission_media
    attributes:
      label: "Supported Transmission Media"
      description: "How are signals transmitted (e.g., Twisted pair, fiber optics, Wireless mesh)?"
      placeholder: "e.g., Fiber optics, ..."

  - type: textarea
    id: related_standards
    attributes:
      label: "Related Standards"
      description: "Specify the standards to which the protocol can be assigned (e.g., IEEE, ISO)."
      placeholder: "e.g., ISO-16484-6, ..."

  - type: checkboxes
    id: open_source_status
    attributes:
      label: "Open-Source Status"
      description: "Is the protocol public and freely available?"
      options:
        - label: "Open Source"
        - label: "Proprietary"

  - type: dropdown
    id: license_fee
    attributes:
      label: "License Fee"
      description: "Is there a fee for using the protocol or certification?"
      options:
        - unknown
        - Fee required
        - No fee required

  - type: input
    id: network_topology
    attributes:
      label: "Network Topology"
      description: "What is the physical and logical arrangement of devices in the network?"
      placeholder: "e.g., star, ..."

  - type: textarea
    id: implemented_security_mechanisms
    attributes:
      label: "Implemented Security Mechanisms"
      description: "What security mechanisms are implemented to ensure data security?"

  - type: input
    id: bandwidth
    attributes:
      label: "Bandwidth"
      description: "What is the communication channel capacity (bandwidth) for transmitting data between the various components of the system?"
      placeholder: "e.g., 100 Mbps"

  - type: input
    id: frequency
    attributes:
      label: "Frequency"
      description: "What frequency or wavelength is used for communication (in wireless systems)?"
      placeholder: "e.g., 2.4 GHz or Not applicable"

  - type: input
    id: range
    attributes:
      label: "Range"
      description: "the maximum distance over which communication can be maintained between the various devices and components of the system without the signal strength becoming too weak."
      placeholder: "e.g., 50 meters"

  - type: checkboxes
    id: implemented_osi_layer
    attributes:
      label: "Implemented OSI-layer"
      description: "Which OSI reference model layers are applied for communication between the various components of the system in the protocol? Multiple choices allowed."
      options: 
        - label: "Application layer"
        - label: "Presentation layer"
        - label: "Session layer"
        - label: "Transport layer"
        - label: "Network/Packet layer"
        - label: "Data Link layer"
        - label: "Physical layer"

  - type: checkboxes
    id: levels_of_building_automation
    attributes:
      label: "Levels of Building Automation"
      description: "Describe the hierarchical structure for building automation system where the protocol is applied. Multiple choices allowed."
      options: 
        - label: "field level"
        - label: "automation level"
        - label: "management level"

  - type: input
    id: data_model_architecture
    attributes:
      label: "Data Model Architecture"
      description: "How is information or attributes added to an object in the system?"

  - type: dropdown
    id: discovery
    attributes:
      label: "Discovery"
      description: "Does the protocol has the “discovery” function to automatically identify devices during data transfer?"
      options:
        - 'Yes'
        - 'No'

  - type: dropdown
    id: multi_master
    attributes:
      label: "Multi Master"
      description: "Can multiple master devices operate simultaneously?"
      options:
        - 'Yes'
        - 'No'

  - type: textarea
    id: priority
    attributes:
      label: "Priority"
      description: "How are changes or updates managed within the protocol (priority handling)?"
      placeholder: "e.g., Priority-based scheduling"

  - type: textarea
    id: typical_application
    attributes:
      label: "Typical Application"
      description: "If applicable, provide an example of how the protocol is used in a real-world scenario."
      placeholder: "e.g., Used in building management systems"

  - type: textarea
    id: link
    attributes:
      label: "Link"
      description: "Please provide a link for further information about the protocol."
