name: "Tools/Application's Data Contribution"
description: "Template for submitting data about tools/applications"
title: "[Tool Name]: Feature Request"
labels: ["Tools Contribution"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Template for Tools/Application's Data Contribution

  - type: input
    id: tool_name
    attributes:
      label: "Name of the Tool/Application"
      description: "Please provide the name of the tool/application."
      placeholder: "e.g., AixWeather"

  - type: textarea
    id: short_description
    attributes:
      label: "Short Description"
      description: "Briefly describe the application (2-3 sentences)."
      placeholder: "e.g., A tool that simulates weather conditions for planning purposes."

  - type: input
    id: resources
    attributes:
      label: "Resources (Documentation, Literature, Git Repositories, etc.)"
      description: "List relevant resources such as documentation, literature, or Git repositories associated with the application."
      placeholder: "e.g., https://github.com/tool-repo, Documentation PDF"

  - type: checkboxes
    id: application_area
    attributes:
      label: "Application Area"
      description: "Select the relevant application area(s). Multiple choices allowed."
      options:
        - label: "Administration"
        - label: "Research/Teaching"
        - label: "Industry"
        - label: "Services"

  - type: input
    id: provider
    attributes:
      label: "Provider (Vendor)"
      description: "Name of the tool provider or company."
      placeholder: "e.g., Highsoft"

  - type: checkboxes
    id: usage_type
    attributes:
      label: "Usage Type"
      description: "Describe how the tool is used (e.g., monitoring, optimization, planning)."
      options:
        - label: "Simulation"
        - label: "Monitoring"
        - label: "Optimization"
        - label: "Planning"
        - label: "Control"

  - type: checkboxes
    id: lifecycle_phase
    attributes:
      label: "Lifecycle Phase"
      description: "Which phases of a project does this tool apply to? Multiple choices allowed."
      options:
        - label: "Pre-planning"
        - label: "Planning"
        - label: "Implementation"
        - label: "Operation"

  - type: checkboxes
    id: target_group
    attributes:
      label: "Target Group"
      description: "Specify the main user group(s) for the tool."
      options:
        - label: "Construction professionals"
        - label: "Engineers"
        - label: "IT professionals/Software developers"
        - label: "End users"

  - type: checkboxes
    id: user_interface
    attributes:
      label: "User Interface"
      description: "Describe the user interface of the tool."
      options:
        - label: "web-based UI"
        - label: "graphical UI"
        - label: "command-line interface"


  - type: textarea
    id: user_interface_notes
    attributes:
      label: "User Interface Notes"
      description: "Provide any additional notes about the user interface."
      placeholder: "Any specific notes about the UI"

  - type: checkboxes
    id: programming_languages
    attributes:
      label: "Programming Languages"
      description: "List the programming languages used by the tool. Multiple choices allowed."
      options:
        - label: "Python"
        - label: "Matlab"
        - label: "R"
        - label: "C"
        - label: "C++"
        - label: "Java"

  - type: checkboxes
    id: frameworks_libraries
    attributes:
      label: "Frameworks/Libraries"
      description: "Mention any frameworks or libraries the tool depends on. Multiple choices allowed."
      options:
        - label: "Django"
        - label: "React"
        - label: "Flask"
        - label: "Angular"

  - type: checkboxes
    id: database_systems
    attributes:
      label: "Database Systems"
      description: "List any database systems the tool interacts with. Multiple choices allowed."
      options:
        - label: "MySQL"
        - label: "PostgreSQL"
        - label: "MongoDB"

  - type: checkboxes
    id: type_of_application
    attributes:
      label: "Type of Application"
      description: "Classify the tool (e.g., digital application, digital tool, framework, platform). Multiple choices allowed."
      options:
        - label: "Digital Application"
        - label: "Digital Tool"
        - label: "Framework/Library"
        - label: "Platform"

  - type: checkboxes
    id: focus
    attributes:
      label: "Focus"
      description: "Specify the focus area(s) of the tool. Multiple choices allowed."
      options:
        - label: "Technical"
        - label: "Operational"
        - label: "Ecological"
        - label: "Legal"

  - type: checkboxes
    id: scale
    attributes:
      label: "Scale"
      description: "Describe the scale at which the tool is applied. Multiple choices allowed."
      options:
        - label: "Component"
        - label: "System"
        - label: "Building"
        - label: "District/Networks"
        - label: "Region/Country"

  - type: input
    id: last_update
    attributes:
      label: "Last Update"
      description: "Provide the date of the latest update for this tool."
      placeholder: "e.g., 2024-10-21"

  - type: checkboxes
    id: accessibility
    attributes:
      label: "Accessibility"
      description: "Indicate the accessibility of the tool (e.g., paid, open-source, freeware)."
      options:
        - label: "Paid"
        - label: "Open-source"
        - label: "Freeware"

  - type: input
    id: license
    attributes:
      label: "License"
      description: "Specify the license under which the tool is distributed."
      placeholder: "e.g., MIT, GNU, Apache License 2.0"

  - type: textarea
    id: license_notes
    attributes:
      label: "License Notes"
      description: "Provide any additional notes regarding the license."

  - type: textarea
    id: further_information
    attributes:
      label: "Further Information"
      description: "Any further relevant details or references about the tool."

  - type: input
    id: alternatives
    attributes:
      label: "Alternatives"
      description: "List any alternative tools."
      placeholder: "e.g., D3.js, Chart.js"

  - type: input
    id: specific_application_in_projects
    attributes:
      label: "Specific Application in Projects"
      description: "If used in specific projects, provide a reference or ID."
      placeholder: "e.g., 03EN1011"

  - type: input
    id: year_of_release
    attributes:
      label: "Year of Release"
      description: "Indicate the release year of the tool."
      placeholder: "e.g., 2009"

  - type: input
    id: development_state
    attributes:
      label: "Development State (1-5)"
      description: "Rate the development state of the tool (1-5)."
      placeholder: "e.g., 4"

  - type: textarea
    id: technical_standards
    attributes:
      label: "Technical Standards"
      description: "Mention any technical standards or protocols the tool follows."

  - type: checkboxes
    id: released
    attributes:
      label: "Released (Boolean - 1/0)"
      description: "Has the tool been officially released?"
      options:
        - label: "Yes"
        - label: "No"

  - type: checkboxes
    id: planned_release
    attributes:
      label: "Planned Release (Boolean - 1/0)"
      description: "Is a release planned but not yet completed?"
      options:
        - label: "Yes"
        - label: "No"