# Generated by Django 5.0.9 on 2024-12-10 12:54

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
                (
                    "updateDate",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Norm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Name of the item", max_length=200
                    ),
                ),
                (
                    "name_de",
                    models.CharField(
                        db_comment="Name of the item", max_length=200, null=True
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        db_comment="Name of the item", max_length=200, null=True
                    ),
                ),
                (
                    "alternatives",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "alternatives_de",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "alternatives_en",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "developmentState",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "pre-alpha"),
                            (2, "alpha"),
                            (3, "beta"),
                            (4, "release candidate"),
                            (5, "release"),
                        ],
                        db_comment="Level of development - What is the curent development status",
                        null=True,
                    ),
                ),
                (
                    "furtherInformation",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "furtherInformation_de",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "furtherInformation_en",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_comment="File name of image file. Located in media-folder.",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "released",
                    models.BooleanField(
                        blank=True,
                        db_comment="Released - Is the publication done?",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "provider_de",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "provider_en",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "resources",
                    models.CharField(
                        blank=True,
                        db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease_de",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease_en",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        db_comment="full title  of the norm",
                        help_text="title of the norm",
                        max_length=250,
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True,
                        db_comment="full title  of the norm",
                        help_text="title of the norm",
                        max_length=250,
                        null=True,
                    ),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True,
                        db_comment="full title  of the norm",
                        help_text="title of the norm",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
