# Generated by Django 5.0.9 on 2024-11-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0001_initial"),
        ("tools_over", "0008_alter_tools_technicalstandardsprotocols"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Protocol",
        ),
    ]
