# Generated by Django 5.0.9 on 2024-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0002_delete_protocol"),
        ("common", "0006_license_licensingfeerequirement_de_and_more"),
        ("tools_over", "0008_alter_tools_technicalstandardsprotocols"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="accessibility",
            field=models.ManyToManyField(
                db_comment="Accessibility - How accessible is the dataset?",
                to="tools_over.accessibility",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="alternatives",
            field=models.CharField(
                blank=True,
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="applicationArea",
            field=models.ManyToManyField(
                db_comment="Typical application area in which the item is used.",
                to="tools_over.applicationarea",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of item - Which type or of to which typ belongs the item. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="developmentState",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "pre-alpha"),
                    (2, "alpha"),
                    (3, "beta"),
                    (4, "release candidate"),
                    (5, "release"),
                ],
                db_comment="Level of development - What is the curent development status",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="focus",
            field=models.ManyToManyField(
                db_comment="Focus identifier - Selected focus (Definied by Wissensplattform)",
                max_length=200,
                to="tools_over.focus",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="furtherInformation",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="image",
            field=models.ImageField(
                blank=True,
                db_comment="File name of image file. Located in media-folder.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="license",
            field=models.ManyToManyField(
                db_comment="under which license was the dataset published and are there any costs associated with using the dataset?",
                to="common.license",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="lifeCyclePhase",
            field=models.ManyToManyField(
                db_comment="Life cycle phase - In which phase of the product life cycle is the tool used?",
                to="tools_over.lifecyclephase",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="programmingLanguages",
            field=models.CharField(
                blank=True,
                db_comment="Programming languages - Which programming languages are mainly used to implment the item.",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="provider",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="released",
            field=models.BooleanField(
                blank=True,
                db_comment="Released - Is the publication done?",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="scale",
            field=models.ManyToManyField(
                db_comment="Spatial scale of the use cases - On what scale is the dataset used?",
                to="tools_over.scale",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="targetGroup",
            field=models.ManyToManyField(
                db_comment="Target group - Who do you say the digital item is aimed at?",
                to="tools_over.targetgroup",
            ),
        ),
    ]
