# Generated by Django 5.0.9 on 2024-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0003_norm_accessibility_norm_alternatives_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="link",
        ),
        migrations.AddField(
            model_name="norm",
            name="resources",
            field=models.CharField(
                blank=True, help_text="link", max_length=1000
            ),
        ),
    ]
