# Generated by Django 5.0.9 on 2024-11-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0004_remove_norm_link_norm_resources"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="shortDescription",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="shortDescription_de",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="shortDescription_en",
        ),
        migrations.AddField(
            model_name="norm",
            name="description",
            field=models.TextField(
                blank=True,
                db_comment="Description of the item.",
                default=None,
                help_text="short description",
                max_length=1000,
                null=True,
            ),
        ),
    ]
