# Generated by Django 5.0.9 on 2024-11-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0005_remove_norm_shortdescription_and_more"),
        (
            "project_listing",
            "0003_alter_enargus_randdplanningcategory_and_more",
        ),
        ("tools_over", "0008_alter_tools_technicalstandardsprotocols"),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="specificApplication",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Specific use cases - Identification of concrete examples of the use of the item in the construction sector/energy transition (equals project number)",
                to="project_listing.subproject",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="usage",
            field=models.ManyToManyField(
                db_comment="Use type - What purpose is the item used for? (Simulation, monitoring, optimization, planning, control advanced control)",
                to="tools_over.usage",
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="yearOfRelease",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
    ]
