# Generated by Django 5.0.9 on 2024-11-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0006_norm_specificapplication_norm_usage_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="isNorm",
        ),
    ]
