# Generated by Django 5.0.9 on 2024-11-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0007_remove_norm_isnorm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norm",
            name="alternatives",
            field=models.CharField(
                blank=True,
                db_comment="Alternatives - items with equal or likewise use case.",
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name",
            field=models.CharField(
                blank=True,
                db_comment="Name of the item",
                help_text="name of the norm",
                max_length=150,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name_de",
            field=models.CharField(
                blank=True,
                db_comment="Name of the item",
                help_text="name of the norm",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name_en",
            field=models.CharField(
                blank=True,
                db_comment="Name of the item",
                help_text="name of the norm",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="resources",
            field=models.CharField(
                blank=True,
                db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                help_text="link",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="title",
            field=models.CharField(
                blank=True,
                db_comment="full title  of the norm",
                help_text="title of the norm",
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="title_de",
            field=models.CharField(
                blank=True,
                db_comment="full title  of the norm",
                help_text="title of the norm",
                max_length=250,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="title_en",
            field=models.CharField(
                blank=True,
                db_comment="full title  of the norm",
                help_text="title of the norm",
                max_length=250,
                null=True,
            ),
        ),
    ]
