# Generated by Django 5.0.9 on 2024-11-19 07:10

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0008_alter_norm_alternatives_alter_norm_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
                (
                    "updateDate",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="norm",
            name="source",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="source_de",
        ),
        migrations.RemoveField(
            model_name="norm",
            name="source_en",
        ),
        migrations.AddField(
            model_name="norm",
            name="description_de",
            field=models.TextField(
                blank=True,
                db_comment="Description of the item.",
                default=None,
                help_text="short description",
                max_length=1000,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="description_en",
            field=models.TextField(
                blank=True,
                db_comment="Description of the item.",
                default=None,
                help_text="short description",
                max_length=1000,
                null=True,
            ),
        ),
    ]
