# Generated by Django 5.0.9 on 2024-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0009_history_remove_norm_source_remove_norm_source_de_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="norm",
            name="alternatives_de",
            field=models.CharField(
                blank=True,
                db_comment="Alternatives - items with equal or likewise use case.",
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="alternatives_en",
            field=models.CharField(
                blank=True,
                db_comment="Alternatives - items with equal or likewise use case.",
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="furtherInformation_de",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="furtherInformation_en",
            field=models.CharField(
                blank=True,
                db_comment="Further information - Information of miscellaneous subjects",
                max_length=1200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="provider_de",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="provider_en",
            field=models.CharField(
                blank=True,
                db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="yearOfRelease_de",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="norm",
            name="yearOfRelease_en",
            field=models.CharField(
                blank=True,
                db_comment="Year of publication - If the item is published, in which year was it released?",
                help_text="year of software release (planned or conducted)",
                max_length=100,
                null=True,
            ),
        ),
    ]
