# Generated by Django 5.0.9 on 2024-11-25 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0010_norm_alternatives_de_norm_alternatives_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="norm",
            name="resources",
            field=models.CharField(
                blank=True,
                db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                help_text="link",
                max_length=1000,
                null=True,
            ),
        ),
    ]
