# Generated by Django 5.0.9 on 2024-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TechnicalStandards", "0011_alter_norm_resources"),
        ("common", "0006_license_licensingfeerequirement_de_and_more"),
        ("tools_over", "0009_remove_tools_license_tools_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="norm",
            name="alternatives",
            field=models.CharField(
                blank=True,
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="alternatives_de",
            field=models.CharField(
                blank=True,
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="alternatives_en",
            field=models.CharField(
                blank=True,
                help_text="Alternatives - Items with equal or likewise use case.",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of dataset - Which type or of to which typ belongs the dataset. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="description_de",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="description_en",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="license",
            field=models.ManyToManyField(
                db_comment="under which license was the item published and are there any costs associated with using the dataset?",
                to="common.license",
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name",
            field=models.CharField(
                db_comment="Name of the item", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name_de",
            field=models.CharField(
                db_comment="Name of the item", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="name_en",
            field=models.CharField(
                db_comment="Name of the item", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="norm",
            name="resources",
            field=models.CharField(
                blank=True,
                db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                max_length=1000,
                null=True,
            ),
        ),
    ]
