# Generated by Django 5.0.9 on 2024-12-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0012_alter_norm_alternatives_alter_norm_alternatives_de_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="norm",
            name="programmingLanguages",
        ),
    ]
