# Generated by Django 4.2.1 on 2024-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_integration", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userengagement",
            name="procedureItem_de",
        ),
        migrations.RemoveField(
            model_name="userengagement",
            name="procedureItem_en",
        ),
        migrations.AddField(
            model_name="procedureitem",
            name="procedureItem_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="procedureitem",
            name="procedureItem_en",
            field=models.TextField(null=True),
        ),
    ]
