# Generated by Django 4.2.1 on 2024-08-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conargument",
            name="conArgument_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="conargument",
            name="conArgument_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="literature",
            name="literature_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="literature",
            name="literature_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="proargument",
            name="proArgument_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="proargument",
            name="proArgument_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="categoryShortDescription_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="categoryShortDescription_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="category_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="category_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="goals_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="goals_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="goodPracticeExample_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="goodPracticeExample_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="groupSize_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="groupSize_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="material_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="material_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="procedure_de",
            field=models.ManyToManyField(
                blank=True, null=True, to="user_integration.procedureitem"
            ),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="procedure_en",
            field=models.ManyToManyField(
                blank=True, null=True, to="user_integration.procedureitem"
            ),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="subCategoryShortDescription_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="subCategoryShortDescription_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="timeRequired_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userengagement",
            name="timeRequired_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
