# Generated by Django 4.2.1 on 2024-08-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_integration", "0002_conargument_conargument_de_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="literature",
            name="literature_de",
        ),
        migrations.RemoveField(
            model_name="literature",
            name="literature_en",
        ),
    ]
