# Generated by Django 4.2.1 on 2024-04-25 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('text', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.CharField(max_length=5000)),
                ('imageFilename', models.CharField(blank=True, max_length=200, null=True)),
                ('criteriaCatalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='criteriaCatalog.criteriacatalog')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='criteriaCatalog.topic')),
                ('tag', models.ManyToManyField(blank=True, to='criteriaCatalog.tag')),
            ],
        ),
    ]
