# Generated by Django 4.2.1 on 2024-05-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriacatalog',
            name='imageIcon',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
