# Generated by Django 4.2.1 on 2024-08-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0002_topic_norms'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='grey',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
