# Generated by Django 4.2.1 on 2024-05-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0002_criteriacatalog_imageicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteriacatalog',
            name='imageIconSelected',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
