# Generated by Django 4.2.1 on 2024-06-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0003_criteriacatalog_imageiconselected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='heading',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.TextField(),
        ),
    ]
