# Generated by Django 4.2.1 on 2024-06-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0004_alter_topic_heading_alter_topic_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
