# Generated by Django 4.2.1 on 2024-06-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0005_alter_topic_heading'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topicHeadingNumber',
            field=models.CharField(blank=True, null=True),
        ),
    ]
