# Generated by Django 4.2.1 on 2024-06-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteriaCatalog', '0006_topic_topicheadingnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
