# Generated by Django 4.2.1 on 2024-08-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('criteria_catalog', '0003_topic_grey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriacatalog',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
