# Generated by Django 4.2.1 on 2024-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criteria_catalog", "0004_alter_criteriacatalog_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteriacatalog",
            name="name_de",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="criteriacatalog",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="criteriacatalog",
            name="text_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criteriacatalog",
            name="text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_de",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="heading_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="heading_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="text_de",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="text_en",
            field=models.TextField(null=True),
        ),
    ]
