# Generated by Django 3.2.18 on 2023-07-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_service', models.CharField(blank=True, help_text='Name der Anwendung', max_length=150)),
                ('short_description', models.CharField(blank=True, help_text='Kurzbeschreibung des DatenService', max_length=1000)),
                ('provider', models.CharField(blank=True, help_text='Provider des DatenService', max_length=150)),
                ('further_information', models.CharField(blank=True, help_text='weitere Informationen zum DatenService', max_length=500)),
                ('data_url', models.CharField(blank=True, help_text='Url zum Datensatz', max_length=300)),
                ('logo_url', models.CharField(blank=True, help_text='Url zum Logo', max_length=300)),
                ('applications', models.CharField(blank=True, help_text='konkrete Anwendung der Datensätze bzw. der Werkzeuge', max_length=500)),
                ('last_update', models.CharField(blank=True, help_text='letztes Update des DatenServices', max_length=100)),
                ('license', models.CharField(blank=True, help_text='Lizenz des DatenServices', max_length=200)),
                ('category', models.CharField(blank=True, help_text='Kategorie des DatenServices (Datensatz, Anwendung, ...)', max_length=150)),
                ('long_description', models.CharField(blank=True, help_text='Beschreibung des DatenService', max_length=10000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
