# Generated by Django 4.0.3 on 2022-03-30 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weatherdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_service', models.CharField(blank=True, help_text='Name der Anwendung', max_length=150)),
                ('short_description', models.CharField(help_text='Kurzbeschreibung des DatenService', max_length=1000)),
                ('provider', models.CharField(blank=True, help_text='Provider des DatenService', max_length=150)),
                ('further_information', models.CharField(blank=True, help_text='weitere Informationen zur Anwendung', max_length=500)),
                ('data_url', models.CharField(blank=True, help_text='Url zu Datensatz', max_length=300)),
                ('logo_url', models.CharField(blank=True, help_text='Logo url', max_length=300)),
                ('applications', models.CharField(blank=True, help_text='Anwendung in EWB Projekten', max_length=500)),
                ('last_update', models.CharField(blank=True, help_text='letztes Update der Anwendung', max_length=100)),
                ('license', models.CharField(blank=True, help_text='Lizenz der Anwendung', max_length=200)),
            ],
        ),
    ]
