# Generated by Django 4.0.3 on 2022-03-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata_over', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='category',
            field=models.CharField(blank=True, help_text='Kategorie des DatenServices (Datensatz, Anwendung, ...)', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='further_information',
            field=models.CharField(blank=True, help_text='weitere Informationen zum DatenService', max_length=500),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='last_update',
            field=models.CharField(blank=True, help_text='letztes Update des DatenServices', max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='license',
            field=models.CharField(blank=True, help_text='Lizenz des DatenServices', max_length=200),
        ),
    ]
