# Generated by Django 3.2.9 on 2022-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata_over', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='applications',
            field=models.CharField(blank=True, help_text='konkrete Anwendung der Datensätze bzw. der Werkzeuge', max_length=500),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='data_url',
            field=models.CharField(blank=True, help_text='Url zum Datensatz', max_length=300),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='logo_url',
            field=models.CharField(blank=True, help_text='Url zum Logo', max_length=300),
        ),
    ]
