# Generated by Django 4.0.3 on 2022-03-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherdata_over', '0002_weatherdata_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='category',
            field=models.CharField(blank=True, help_text='Kategorie des DatenServices (Datensatz, Anwendung, ...)', max_length=150),
        ),
    ]
