# Generated by Django 5.0.9 on 2024-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tools_over", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UseCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_code", models.CharField(max_length=25)),
                ("useCase", models.CharField(max_length=50)),
                ("useCase_de", models.CharField(max_length=50, null=True)),
                ("useCase_en", models.CharField(max_length=50, null=True)),
                (
                    "sriLevel",
                    models.CharField(
                        max_length=255, verbose_name="SRI-Zuordnung"
                    ),
                ),
                (
                    "sriLevel_de",
                    models.CharField(
                        max_length=255, null=True, verbose_name="SRI-Zuordnung"
                    ),
                ),
                (
                    "sriLevel_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="SRI-Zuordnung"
                    ),
                ),
                ("levelOfAction", models.CharField(max_length=100)),
                (
                    "levelOfAction_de",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "levelOfAction_en",
                    models.CharField(max_length=100, null=True),
                ),
                ("degreeOfDetail", models.CharField(max_length=100)),
                (
                    "degreeOfDetail_de",
                    models.CharField(max_length=100, null=True),
                ),
                (
                    "degreeOfDetail_en",
                    models.CharField(max_length=100, null=True),
                ),
                ("idPerspectiveforDetail", models.PositiveIntegerField()),
                (
                    "idPerspectiveforDetail_de",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "idPerspectiveforDetail_en",
                    models.PositiveIntegerField(null=True),
                ),
                (
                    "effectEvaluation",
                    models.CharField(
                        choices=[
                            ("+", "Positive"),
                            ("-", "Negative"),
                            ("o", "Neutrale"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "effectEvaluation_de",
                    models.CharField(
                        choices=[
                            ("+", "Positive"),
                            ("-", "Negative"),
                            ("o", "Neutrale"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "effectEvaluation_en",
                    models.CharField(
                        choices=[
                            ("+", "Positive"),
                            ("-", "Negative"),
                            ("o", "Neutrale"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("effectName", models.CharField(max_length=255)),
                ("effectName_de", models.CharField(max_length=255, null=True)),
                ("effectName_en", models.CharField(max_length=255, null=True)),
                ("effectDescription", models.TextField()),
                ("effectDescription_de", models.TextField(null=True)),
                ("effectDescription_en", models.TextField(null=True)),
                ("furtherInformation", models.TextField(blank=True, null=True)),
                (
                    "furtherInformation_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "furtherInformation_en",
                    models.TextField(blank=True, null=True),
                ),
                ("icon", models.TextField(blank=True, null=True)),
                ("focus", models.ManyToManyField(to="tools_over.focus")),
            ],
        ),
    ]
