# Generated by Django 5.0.9 on 2024-12-11 07:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DbDiff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(max_length=100)),
                ("diffStr", models.TextField()),
                ("executed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
                (
                    "updateDate",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "license_de",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "license_en",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "openSourceStatus",
                    models.CharField(
                        blank=True,
                        help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "openSourceStatus_de",
                    models.CharField(
                        blank=True,
                        help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "openSourceStatus_en",
                    models.CharField(
                        blank=True,
                        help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "licensingFeeRequirement",
                    models.CharField(
                        blank=True,
                        help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "licensingFeeRequirement_de",
                    models.CharField(
                        blank=True,
                        help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "licensingFeeRequirement_en",
                    models.CharField(
                        blank=True,
                        help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                        max_length=150,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("literature", models.TextField()),
                (
                    "linkName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
