# Generated by Django 4.2.1 on 2024-08-20 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dbdiff",
            old_name="identifer",
            new_name="identifier",
        ),
    ]
