# Generated by Django 4.2.1 on 2024-08-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_rename_identifer_dbdiff_identifier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Literature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("literature", models.TextField()),
                (
                    "linkName",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
    ]
