# Generated by Django 5.0.9 on 2024-11-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_literature"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license", models.CharField(max_length=300)),
                ("license_de", models.CharField(max_length=300, null=True)),
                ("license_en", models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
