# Generated by Django 5.0.9 on 2024-11-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="licensingFeeRequirement",
            field=models.CharField(
                blank=True,
                help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="openSourceStatus",
            field=models.CharField(
                blank=True,
                help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                max_length=50,
            ),
        ),
    ]
