# Generated by Django 5.0.9 on 2024-11-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_license_licensingfeerequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="license",
            name="licensingFeeRequirement_de",
            field=models.CharField(
                blank=True,
                help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="licensingFeeRequirement_en",
            field=models.CharField(
                blank=True,
                help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="openSourceStatus_de",
            field=models.CharField(
                blank=True,
                help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="license",
            name="openSourceStatus_en",
            field=models.CharField(
                blank=True,
                help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="license",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_de",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="license_en",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="license",
            name="licensingFeeRequirement",
            field=models.CharField(
                blank=True,
                help_text="Lizenzgebühr (Gebühr zur Abdeckung der Kosten für Tests und Zertifizierung)",
                max_length=150,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="license",
            name="openSourceStatus",
            field=models.CharField(
                blank=True,
                help_text="Open-Source-Status (Ob Spezifikationen öffentlich und frei verfügbar sind oder nicht)",
                max_length=50,
                null=True,
            ),
        ),
    ]
