# Generated by Django 5.0.9 on 2024-12-11 07:35

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifer", models.CharField(max_length=300)),
                ("stringifiedObj", models.TextField()),
                ("loaded", models.BooleanField(default=False)),
                (
                    "updateDate",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Protocol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="Name of the item", max_length=200
                    ),
                ),
                (
                    "alternatives",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "alternatives_de",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "alternatives_en",
                    models.CharField(
                        blank=True,
                        help_text="Alternatives - Items with equal or likewise use case.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "developmentState",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "pre-alpha"),
                            (2, "alpha"),
                            (3, "beta"),
                            (4, "release candidate"),
                            (5, "release"),
                        ],
                        db_comment="Level of development - What is the curent development status",
                        null=True,
                    ),
                ),
                (
                    "furtherInformation",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "furtherInformation_de",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "furtherInformation_en",
                    models.CharField(
                        blank=True,
                        db_comment="Further information - Information of miscellaneous subjects",
                        max_length=1200,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        db_comment="File name of image file. Located in media-folder.",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "released",
                    models.BooleanField(
                        blank=True,
                        db_comment="Released - Is the publication done?",
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "provider_de",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "provider_en",
                    models.CharField(
                        blank=True,
                        db_comment="Developers/maintainers/provider - Person or organisation responsible for the development of the item.",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "resources",
                    models.CharField(
                        blank=True,
                        db_comment="Sources of information - sources for further information about the item e.g. git repo, project website, ...",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "description_de",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "description_en",
                    models.CharField(
                        blank=True,
                        db_comment="Description of the item",
                        max_length=1100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease_de",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "yearOfRelease_en",
                    models.CharField(
                        blank=True,
                        db_comment="Year of publication - If the item is published, in which year was it released?",
                        help_text="year of software release (planned or conducted)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "communicationMediumCategory",
                    models.CharField(
                        blank=True,
                        db_comment="Transmission category - How is data transfered between the various components and devices within the system (wired, wireless or wired & wireless)",
                        help_text="Übertragungsmethoden (verkabelt, drahtlos oder verkabelt und drahtlos)",
                        max_length=150,
                    ),
                ),
                (
                    "communicationMediumCategory_de",
                    models.CharField(
                        blank=True,
                        db_comment="Transmission category - How is data transfered between the various components and devices within the system (wired, wireless or wired & wireless)",
                        help_text="Übertragungsmethoden (verkabelt, drahtlos oder verkabelt und drahtlos)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "communicationMediumCategory_en",
                    models.CharField(
                        blank=True,
                        db_comment="Transmission category - How is data transfered between the various components and devices within the system (wired, wireless or wired & wireless)",
                        help_text="Übertragungsmethoden (verkabelt, drahtlos oder verkabelt und drahtlos)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "supportedTransmissionMediuems",
                    models.CharField(
                        blank=True,
                        db_comment="Supported transmission media - how are signals transmitted?",
                        help_text="Unterstützte Übertragungsmedien",
                        max_length=150,
                    ),
                ),
                (
                    "supportedTransmissionMediuems_de",
                    models.CharField(
                        blank=True,
                        db_comment="Supported transmission media - how are signals transmitted?",
                        help_text="Unterstützte Übertragungsmedien",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "supportedTransmissionMediuems_en",
                    models.CharField(
                        blank=True,
                        db_comment="Supported transmission media - how are signals transmitted?",
                        help_text="Unterstützte Übertragungsmedien",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "associatedStandards",
                    models.CharField(
                        blank=True,
                        help_text="Zugehörige Standards (Spezifische Standards, denen jedes Protokoll entspricht)",
                        max_length=200,
                    ),
                ),
                (
                    "networkTopology",
                    models.CharField(
                        blank=True,
                        db_comment="Network topology - what is the physical and logical arrangement of devices and components in a network?",
                        help_text="Netzwerktopologie (Physische und logische Anordnung von Geräten in einem Netzwerk)",
                        max_length=150,
                    ),
                ),
                (
                    "networkTopology_de",
                    models.CharField(
                        blank=True,
                        db_comment="Network topology - what is the physical and logical arrangement of devices and components in a network?",
                        help_text="Netzwerktopologie (Physische und logische Anordnung von Geräten in einem Netzwerk)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "networkTopology_en",
                    models.CharField(
                        blank=True,
                        db_comment="Network topology - what is the physical and logical arrangement of devices and components in a network?",
                        help_text="Netzwerktopologie (Physische und logische Anordnung von Geräten in einem Netzwerk)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "security",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented security mechanisms - whether and what mechanisms are implemented in the protocol to ensure data security?",
                        help_text="Implementierte Sicherheitmechanismen",
                        max_length=150,
                    ),
                ),
                (
                    "security_de",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented security mechanisms - whether and what mechanisms are implemented in the protocol to ensure data security?",
                        help_text="Implementierte Sicherheitmechanismen",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "security_en",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented security mechanisms - whether and what mechanisms are implemented in the protocol to ensure data security?",
                        help_text="Implementierte Sicherheitmechanismen",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "bandwidth",
                    models.CharField(
                        blank=True,
                        db_comment="Bandwidth - The capacity of the communication channel to transmit data between the various components of the system.",
                        help_text="Bandbreite",
                        max_length=150,
                    ),
                ),
                (
                    "bandwidth_de",
                    models.CharField(
                        blank=True,
                        db_comment="Bandwidth - The capacity of the communication channel to transmit data between the various components of the system.",
                        help_text="Bandbreite",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "bandwidth_en",
                    models.CharField(
                        blank=True,
                        db_comment="Bandwidth - The capacity of the communication channel to transmit data between the various components of the system.",
                        help_text="Bandbreite",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True, help_text="Frequenz", max_length=100
                    ),
                ),
                (
                    "frequency_de",
                    models.CharField(
                        blank=True,
                        help_text="Frequenz",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "frequency_en",
                    models.CharField(
                        blank=True,
                        help_text="Frequenz",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "range",
                    models.CharField(
                        blank=True,
                        db_comment="Range - the maximum distance over which communication can be mainained between the various devices and components of the system without the signal strength becoming to weak.",
                        help_text="Reichweite",
                        max_length=150,
                    ),
                ),
                (
                    "range_de",
                    models.CharField(
                        blank=True,
                        db_comment="Range - the maximum distance over which communication can be mainained between the various devices and components of the system without the signal strength becoming to weak.",
                        help_text="Reichweite",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "range_en",
                    models.CharField(
                        blank=True,
                        db_comment="Range - the maximum distance over which communication can be mainained between the various devices and components of the system without the signal strength becoming to weak.",
                        help_text="Reichweite",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "numberOfConnectedDevices",
                    models.CharField(
                        blank=True,
                        db_comment="Maximum devices - maximum number of simultaneous connected devices.",
                        help_text="Geräte (maximale Anzahl an Geräten, die vernetzt werden können)",
                        max_length=5,
                        null=True,
                    ),
                ),
                (
                    "dataModelArchitecture",
                    models.CharField(
                        blank=True,
                        help_text="Datenmodell Architektur (Datenmodell, in dem die Informationen/Attribute zu einem Objekt hinzugefügt werden)",
                        max_length=150,
                    ),
                ),
                (
                    "discovery",
                    models.CharField(
                        blank=True,
                        help_text="Discovery (Funktion, um Geräte im Netzwerk automatisch zu identifzieren)",
                        max_length=10,
                    ),
                ),
                (
                    "discovery_de",
                    models.CharField(
                        blank=True,
                        help_text="Discovery (Funktion, um Geräte im Netzwerk automatisch zu identifzieren)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "discovery_en",
                    models.CharField(
                        blank=True,
                        help_text="Discovery (Funktion, um Geräte im Netzwerk automatisch zu identifzieren)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "multiMaster",
                    models.CharField(
                        blank=True,
                        help_text="Multi Master (Können mehrere Mastergeräte zeitgleich agieren)",
                        max_length=50,
                    ),
                ),
                (
                    "multiMaster_de",
                    models.CharField(
                        blank=True,
                        help_text="Multi Master (Können mehrere Mastergeräte zeitgleich agieren)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "multiMaster_en",
                    models.CharField(
                        blank=True,
                        help_text="Multi Master (Können mehrere Mastergeräte zeitgleich agieren)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "packetSize",
                    models.CharField(
                        blank=True,
                        help_text="Paketgröße (Datenpaketgröße, die nach Maximum Transmission Unit übertragen werden können)",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "priorities",
                    models.CharField(
                        blank=True,
                        db_comment="Priority - Procedure for how the changes or updates are made.",
                        help_text="Priorität  (Vorgehen, wie die Änderungen / Aktualisierungen vorgenommen werden)",
                        max_length=300,
                    ),
                ),
                (
                    "priorities_de",
                    models.CharField(
                        blank=True,
                        db_comment="Priority - Procedure for how the changes or updates are made.",
                        help_text="Priorität  (Vorgehen, wie die Änderungen / Aktualisierungen vorgenommen werden)",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "priorities_en",
                    models.CharField(
                        blank=True,
                        db_comment="Priority - Procedure for how the changes or updates are made.",
                        help_text="Priorität  (Vorgehen, wie die Änderungen / Aktualisierungen vorgenommen werden)",
                        max_length=300,
                        null=True,
                    ),
                ),
                (
                    "price",
                    models.CharField(
                        blank=True,
                        help_text="Kosten, um Hardwareuntersützung für weitere Protokolle zu ermöglichen (Gering, Durchschnittlich, Hoch)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "osiLayers",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented OSI-layer - the application of the layers of the OSI reference model for communication between the various components of the system.",
                        help_text="Implementierte OSI-Schichten (Anwendung [Application], Darstellung [Presentation], Sitzung [Session], Transport [Transport], Vermittlung/Paket [Network], Sicherung [Data Link], Bitübertragung [Phyiscal])",
                        max_length=150,
                    ),
                ),
                (
                    "osiLayers_de",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented OSI-layer - the application of the layers of the OSI reference model for communication between the various components of the system.",
                        help_text="Implementierte OSI-Schichten (Anwendung [Application], Darstellung [Presentation], Sitzung [Session], Transport [Transport], Vermittlung/Paket [Network], Sicherung [Data Link], Bitübertragung [Phyiscal])",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "osiLayers_en",
                    models.CharField(
                        blank=True,
                        db_comment="Implemented OSI-layer - the application of the layers of the OSI reference model for communication between the various components of the system.",
                        help_text="Implementierte OSI-Schichten (Anwendung [Application], Darstellung [Presentation], Sitzung [Session], Transport [Transport], Vermittlung/Paket [Network], Sicherung [Data Link], Bitübertragung [Phyiscal])",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "buildingAutomationLayer",
                    models.CharField(
                        blank=True,
                        db_comment="Levels of building automation - the hierachical structure of building automation system.",
                        help_text="Ebenen der Gebäudeautomation (Feldebene, Automationsebene, Managementebene)",
                        max_length=150,
                    ),
                ),
                (
                    "buildingAutomationLayer_de",
                    models.CharField(
                        blank=True,
                        db_comment="Levels of building automation - the hierachical structure of building automation system.",
                        help_text="Ebenen der Gebäudeautomation (Feldebene, Automationsebene, Managementebene)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "buildingAutomationLayer_en",
                    models.CharField(
                        blank=True,
                        db_comment="Levels of building automation - the hierachical structure of building automation system.",
                        help_text="Ebenen der Gebäudeautomation (Feldebene, Automationsebene, Managementebene)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "exampleProject",
                    models.CharField(
                        blank=True,
                        help_text="Typische Anwendung (Beispielhafte Anwendung)",
                        max_length=250,
                        null=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
