# Generated by Django 5.0.9 on 2024-12-11 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TechnicalStandards", "0002_initial"),
        ("common", "0001_initial"),
        ("project_listing", "0001_initial"),
        ("protocols", "0001_initial"),
        ("tools_over", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="protocol",
            name="accessibility",
            field=models.ManyToManyField(
                db_comment="Accessibility - How accessible is the dataset?",
                to="tools_over.accessibility",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of dataset - Which type or of to which typ belongs the dataset. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="focus",
            field=models.ManyToManyField(
                db_comment="Focus identifier - Selected focus (Definied by Wissensplattform)",
                max_length=200,
                to="tools_over.focus",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="license",
            field=models.ManyToManyField(
                db_comment="under which license was the item published and are there any costs associated with using the dataset?",
                to="common.license",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="lifeCyclePhase",
            field=models.ManyToManyField(
                db_comment="Life cycle phase - In which phase of the product life cycle is the tool used?",
                to="tools_over.lifecyclephase",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="scale",
            field=models.ManyToManyField(
                db_comment="Spatial scale of the use cases - On what scale is the dataset used?",
                to="tools_over.scale",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="specificApplication",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Specific use cases - Identification of concrete examples of the use of the item in the construction sector/energy transition (equals project number)",
                to="project_listing.subproject",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="targetGroup",
            field=models.ManyToManyField(
                db_comment="Target group - Who do you say the digital item is aimed at?",
                to="tools_over.targetgroup",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="technicalStandardsNorms",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Norms - Which norms serve as the basis or orientation for the item?",
                to="TechnicalStandards.norm",
            ),
        ),
        migrations.AddField(
            model_name="protocol",
            name="usage",
            field=models.ManyToManyField(
                db_comment="Use type - What purpose is the item used for? (Simulation, monitoring, optimization, planning, control advanced control)",
                to="tools_over.usage",
            ),
        ),
    ]
