# Generated by Django 5.0.9 on 2024-11-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="associatedTools",
        ),
    ]
