# Generated by Django 5.0.9 on 2024-11-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "TechnicalStandards",
            "0009_history_remove_norm_source_remove_norm_source_de_and_more",
        ),
        (
            "project_listing",
            "0003_alter_enargus_randdplanningcategory_and_more",
        ),
        ("protocols", "0002_remove_protocol_associatedtools"),
        ("tools_over", "0008_alter_tools_technicalstandardsprotocols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of protocol - Which type or of to which typ belongs the dataset. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="focus",
            field=models.ManyToManyField(
                db_comment="Focus identifier - Selected focus (Definied by Wissensplattform)",
                max_length=200,
                to="tools_over.focus",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="specificApplication",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Specific use cases - Identification of concrete examples of the use of the item in the construction sector/energy transition (equals project number)",
                to="project_listing.subproject",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="technicalStandardsNorms",
            field=models.ManyToManyField(
                blank=True,
                db_comment="Norms - Which norms serve as the basis or orientation for the item?",
                to="TechnicalStandards.norm",
            ),
        ),
    ]
