# Generated by Django 5.0.9 on 2024-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_license_licensingfeerequirement_de_and_more"),
        (
            "protocols",
            "0003_alter_protocol_classification_alter_protocol_focus_and_more",
        ),
        ("tools_over", "0009_remove_tools_license_tools_license"),
    ]

    operations = [
        migrations.AlterField(
            model_name="protocol",
            name="classification",
            field=models.ManyToManyField(
                db_comment="General type of dataset - Which type or of to which typ belongs the dataset. E.g. framework, programming language, ...",
                to="tools_over.classification",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="description_de",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="description_en",
            field=models.CharField(
                blank=True,
                db_comment="Description of the item",
                max_length=1100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="image",
            field=models.ImageField(
                blank=True,
                db_comment="File name of image file. Located in media-folder.",
                null=True,
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="license",
            field=models.ManyToManyField(
                db_comment="under which license was the item published and are there any costs associated with using the dataset?",
                to="common.license",
            ),
        ),
        migrations.AlterField(
            model_name="protocol",
            name="name",
            field=models.CharField(
                db_comment="Name of the item", max_length=200
            ),
        ),
    ]
