# Generated by Django 5.0.9 on 2024-12-02 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("protocols", "0004_alter_protocol_classification_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="protocol",
            name="programmingLanguages",
        ),
    ]
