# Generated by Django 4.2.1 on 2024-07-11 11:06

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql._elements_constructors


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "keyword_id",
                    models.AutoField(
                        help_text="Auto.generiert ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        blank=True, help_text="keyword", max_length=200
                    ),
                ),
                (
                    "keywordDefiniton",
                    models.CharField(
                        blank=True,
                        help_text="Definition of the keyword",
                        max_length=1500,
                    ),
                ),
                (
                    "literature",
                    models.CharField(
                        blank=True,
                        help_text="Literature for the keyword",
                        max_length=1500,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="KeywordRegisterFirstReview",
            fields=[
                (
                    "keywordRegisterFirstReview_id",
                    models.AutoField(
                        help_text="Auto.generiert ID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword1",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword1",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword2",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword2",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword3",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword3",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword4",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword4",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword5",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword5",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword6",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword6",
                        to="keywords.keyword",
                    ),
                ),
                (
                    "keyword7",
                    models.ForeignKey(
                        blank=True,
                        null=sqlalchemy.sql._elements_constructors.true,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="keyword7",
                        to="keywords.keyword",
                    ),
                ),
            ],
        ),
    ]
