# Generated by Django 4.2.1 on 2024-07-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSufficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategyCategory', models.CharField(max_length=255)),
                ('strategyCategory_de', models.CharField(max_length=255, null=True)),
                ('strategyCategory_en', models.CharField(max_length=255, null=True)),
                ('categoryShortDescription', models.TextField()),
                ('categoryShortDescription_de', models.TextField(null=True)),
                ('categoryShortDescription_en', models.TextField(null=True)),
                ('example1', models.TextField()),
                ('example1_de', models.TextField(null=True)),
                ('example1_en', models.TextField(null=True)),
                ('example2', models.TextField()),
                ('example2_de', models.TextField(null=True)),
                ('example2_en', models.TextField(null=True)),
            ],
        ),
    ]
