# Generated by Django 4.2.1 on 2024-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sufficiency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasufficiency',
            name='categoryLongDescription',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
