# Generated by Django 4.2.1 on 2024-07-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_sufficiency', '0002_datasufficiency_categorylongdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasufficiency',
            name='categoryLongDescription_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datasufficiency',
            name='categoryLongDescription_en',
            field=models.TextField(null=True),
        ),
    ]
