# Generated by Django 3.2.18 on 2023-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='copyright',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
