# Generated by Django 5.0.9 on 2024-12-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("category_de", models.CharField(max_length=255, null=True)),
                ("category_en", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ComponentClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("componentClass", models.CharField(max_length=255)),
                (
                    "componentClass_de",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "componentClass_en",
                    models.CharField(max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "energyConsumptionUsePhaseTotal",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "globalWarmingPotentialTotal",
                    models.FloatField(blank=True, null=True),
                ),
                ("componentWeight", models.FloatField(blank=True, null=True)),
                ("lifetime", models.IntegerField(blank=True, null=True)),
                (
                    "specificGlobalWarmingPotential",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "energyConsumptionUsePhaseActive",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "powerUseCasePhaseActiveSuperscript",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "energyConsumptionUsePhasePassive",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "globalWarmingPotentialProduction",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "globalWarmingPotentialProdSup",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "globalWarmingPotentialUsePhase",
                    models.FloatField(blank=True, null=True),
                ),
                (
                    "globalWarmingPotentialUsePhaseSup",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "globalWarmingPotentialEndOfLife",
                    models.FloatField(blank=True, null=True),
                ),
                ("furtherInformationNotes", models.TextField(blank=True)),
                (
                    "furtherInformationNotes_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "furtherInformationNotes_en",
                    models.TextField(blank=True, null=True),
                ),
                ("sources", models.TextField(blank=True, null=True)),
                ("sources_de", models.TextField(blank=True, null=True)),
                ("sources_en", models.TextField(blank=True, null=True)),
                ("operationTime", models.IntegerField(blank=True, null=True)),
                (
                    "operationTimeSupscript",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="component_list.category",
                    ),
                ),
                (
                    "componentClass",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="component_list.componentclass",
                    ),
                ),
            ],
        ),
    ]
