# Generated by Django 4.2.1 on 2024-07-11 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('category_de', models.CharField(max_length=255, null=True)),
                ('category_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('componentClass', models.CharField(max_length=255)),
                ('componentClass_de', models.CharField(max_length=255, null=True)),
                ('componentClass_en', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataSufficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategyCategory', models.CharField(max_length=255)),
                ('categoryShortDescription', models.TextField()),
                ('example1', models.TextField()),
                ('example2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name_digital_application', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('partner', models.CharField(max_length=255)),
                ('project_website', models.URLField()),
                ('consortium', models.TextField()),
                ('further', models.TextField(blank=True, null=True)),
                ('digitalApplications', models.TextField()),
                ('goals', models.TextField()),
                ('strategies', models.TextField()),
                ('relevance', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('problem_statement_and_problem_goals', models.TextField()),
                ('implementation_in_the_project', models.TextField()),
                ('evaluation', models.TextField()),
                ('funding_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_listing.subproject')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_de', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('energyConsumptionUsePhaseTotal', models.FloatField(blank=True, null=True)),
                ('globalWarmingPotentialTotal', models.FloatField(blank=True, null=True)),
                ('componentWeight', models.FloatField(blank=True, null=True)),
                ('lifetime', models.IntegerField(blank=True, null=True)),
                ('specificGlobalWarmingPotential', models.FloatField(blank=True, null=True)),
                ('energyConsumptionUsePhaseActive', models.FloatField(blank=True, null=True)),
                ('energyConsumptionUsePhasePassive', models.FloatField(blank=True, null=True)),
                ('globalWarmingPotentialProduction', models.FloatField(blank=True, null=True)),
                ('globalWarmingPotentialUsePhase', models.FloatField(blank=True, null=True)),
                ('globalWarmingPotentialEndOfLife', models.FloatField(blank=True, null=True)),
                ('furtherInformationNotes', models.TextField(blank=True)),
                ('furtherInformationNotes_de', models.TextField(blank=True, null=True)),
                ('furtherInformationNotes_en', models.TextField(blank=True, null=True)),
                ('sources', models.TextField(blank=True, null=True)),
                ('sources_de', models.TextField(blank=True, null=True)),
                ('sources_en', models.TextField(blank=True, null=True)),
                ('yearOfUsePerYear', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_list.category')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='component_list.componentclass')),
            ],
        ),
    ]
