# Generated by Django 4.2.1 on 2024-08-06 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSufficiency',
        ),
        migrations.DeleteModel(
            name='EnvironmentalImpact',
        ),
    ]
