# Generated by Django 4.2.1 on 2024-08-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "component_list",
            "0002_delete_datasufficiency_delete_environmentalimpact",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="component",
            new_name="componentClass",
        ),
    ]
