# Generated by Django 4.2.1 on 2024-08-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("component_list", "0006_remove_component_operationtimesup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="globalWarmingPotentialProdSup",
        ),
        migrations.RemoveField(
            model_name="component",
            name="globalWarmingPotentialUsePhaseSup",
        ),
        migrations.RemoveField(
            model_name="component",
            name="powerUseCasePhaseActiveSuperscript",
        ),
    ]
