# Generated by Django 5.0.9 on 2024-12-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CriteriaCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_de", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
                ("textOverviewBox", models.TextField(blank=True, null=True)),
                ("textOverviewBox_de", models.TextField(blank=True, null=True)),
                ("textOverviewBox_en", models.TextField(blank=True, null=True)),
                ("text", models.TextField(blank=True, null=True)),
                ("text_de", models.TextField(blank=True, null=True)),
                ("text_en", models.TextField(blank=True, null=True)),
                ("imageIcon", models.CharField(blank=True, max_length=200)),
                (
                    "imageIconSelected",
                    models.CharField(blank=True, max_length=200),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("name_de", models.CharField(max_length=100, null=True)),
                ("name_en", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heading", models.TextField(blank=True, null=True)),
                ("heading_de", models.TextField(blank=True, null=True)),
                ("heading_en", models.TextField(blank=True, null=True)),
                ("text", models.TextField()),
                ("text_de", models.TextField(null=True)),
                ("text_en", models.TextField(null=True)),
                ("topicHeadingNumber", models.CharField(blank=True, null=True)),
                (
                    "imageFilename",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "norms",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "grey",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "criteriaCatalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criteria_catalog.criteriacatalog",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="criteria_catalog.topic",
                    ),
                ),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, to="criteria_catalog.tag"
                    ),
                ),
            ],
        ),
    ]
