# Generated by Django 4.2.1 on 2024-09-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "criteria_catalog",
            "0005_criteriacatalog_name_de_criteriacatalog_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="criteriacatalog",
            name="textOverviewBox",
            field=models.TextField(blank=True, null=True),
        ),
    ]
