# Generated by Django 4.2.1 on 2024-09-16 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("criteria_catalog", "0006_criteriacatalog_textoverviewbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="criteriacatalog",
            name="textOverviewBox_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="criteriacatalog",
            name="textOverviewBox_en",
            field=models.TextField(blank=True, null=True),
        ),
    ]
