# Generated by Django 4.2.1 on 2024-05-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('component', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('energyConsumptionUsePhaseTotal', models.FloatField()),
                ('globalWarmingPotentialTotal', models.FloatField()),
                ('componentWeight', models.FloatField()),
                ('lifetime', models.IntegerField()),
                ('energyConsumptionUsePhaseActive', models.FloatField()),
                ('energyConsumptionUsePhasePassive', models.FloatField()),
                ('globalWarmingPotentialProduction', models.FloatField()),
                ('globalWarmingPotentialUsePhase', models.FloatField()),
                ('globalWarmingPotentialEndOfLife', models.FloatField()),
                ('furtherInformationNotes', models.TextField(blank=True)),
                ('sources', models.TextField()),
            ],
        ),
    ]
