# Generated by Django 4.2.1 on 2024-05-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='componentWeight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='energyConsumptionUsePhaseActive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='energyConsumptionUsePhasePassive',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='energyConsumptionUsePhaseTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='globalWarmingPotentialEndOfLife',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='globalWarmingPotentialProduction',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='globalWarmingPotentialTotal',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='globalWarmingPotentialUsePhase',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='lifetime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='sources',
            field=models.TextField(blank=True, null=True),
        ),
    ]
