# Generated by Django 4.2.1 on 2024-08-14 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0003_rename_component_component_componentclass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='yearOfUsePerYear',
            new_name='operationTime',
        ),
    ]
