# Generated by Django 4.2.1 on 2024-05-09 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0003_category_componentclass_alter_component_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='componentclass',
            old_name='name',
            new_name='componentClass',
        ),
    ]
