# Generated by Django 4.2.1 on 2024-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0004_rename_name_category_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='componentclass',
            name='componentClass_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='componentclass',
            name='componentClass_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
