# Generated by Django 4.2.1 on 2024-05-21 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0001_initial'),
        ('component_list', '0005_category_category_de_category_category_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('name_digital_application', models.CharField(max_length=255)),
                ('project_name', models.CharField(max_length=255)),
                ('duration', models.DurationField()),
                ('partner', models.CharField(max_length=255)),
                ('project_website', models.URLField()),
                ('consortium', models.TextField()),
                ('additional_digital_applications', models.TextField()),
                ('goals', models.TextField()),
                ('strategies', models.TextField()),
                ('relevance', models.TextField()),
                ('image', models.CharField(max_length=300)),
                ('problem_statement_and_problem_goals', models.TextField()),
                ('implementation_in_the_project', models.TextField()),
                ('evaluation', models.TextField()),
                ('funding_label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_listing.subproject')),
            ],
        ),
    ]
