# Generated by Django 4.2.1 on 2024-05-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0006_environmentalimpact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='environmentalimpact',
            old_name='additional_digital_applications',
            new_name='digitalApplications',
        ),
        migrations.AddField(
            model_name='environmentalimpact',
            name='further',
            field=models.TextField(blank=True, null=True),
        ),
    ]
