# Generated by Django 4.2.1 on 2024-05-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0007_rename_additional_digital_applications_environmentalimpact_digitalapplications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='environmentalimpact',
            name='duration',
        ),
    ]
