# Generated by Django 4.2.1 on 2024-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0008_remove_environmentalimpact_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSufficiency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategyCategory', models.CharField(max_length=255)),
                ('categoryShortDescription', models.TextField()),
                ('example1', models.TextField()),
                ('example2', models.TextField()),
            ],
        ),
    ]
