# Generated by Django 4.2.1 on 2024-06-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0009_datasufficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='furtherInformationNotes_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='furtherInformationNotes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='sources_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='sources_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='specificGlobalWarmingPotential',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
