# Generated by Django 4.2.1 on 2024-07-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('component_list', '0010_component_description_de_component_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='yearOfUsePerYear',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
