# Generated by Django 3.2.18 on 2024-03-02 18:30

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_listing', '0001_initial'),
        ('TechnicalStandards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LifeCyclePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'UserInterface',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developmentState', models.IntegerField(choices=[(1, 'pre-alpha'), (2, 'alpha'), (3, 'beta'), (4, 'release candidate'), (5, 'release')], null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('accessibility', models.ManyToManyField(to='tools_over.Accessibility')),
                ('applicationArea', models.ManyToManyField(to='tools_over.ApplicationArea')),
                ('classification', models.ManyToManyField(to='tools_over.Classification')),
                ('focus', models.ManyToManyField(to='tools_over.Focus')),
                ('lifeCyclePhase', models.ManyToManyField(to='tools_over.LifeCyclePhase')),
                ('scale', models.ManyToManyField(to='tools_over.Scale')),
                ('targetGroup', models.ManyToManyField(to='tools_over.TargetGroup')),
                ('technicalStandardsNorms', models.ManyToManyField(to='TechnicalStandards.Norm')),
                ('technicalStandardsProtocols', models.ManyToManyField(to='TechnicalStandards.Protocol')),
                ('usage', models.ManyToManyField(to='tools_over.Usage')),
                ('userInterface', models.ManyToManyField(to='tools_over.UserInterface')),
            ],
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UserInterfaceTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('userInterface', models.CharField(blank=True, help_text='userInterface', max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.userinterface')),
            ],
            options={
                'verbose_name': 'UserInterface Translation',
                'db_table': 'tools_over_userinterface_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UsageTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('usage', models.CharField(blank=True, help_text='usage', max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.usage')),
            ],
            options={
                'verbose_name': 'usage Translation',
                'db_table': 'tools_over_usage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ToolsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, help_text='name', max_length=150)),
                ('shortDescription', models.CharField(blank=True, help_text='short description', max_length=1000)),
                ('userInterfaceNotes', models.CharField(blank=True, help_text='additional notes for userInterface', max_length=300)),
                ('lastUpdate', models.CharField(blank=True, help_text='time (year/month/date) of the last update', max_length=100)),
                ('license', models.CharField(blank=True, help_text='license', max_length=500)),
                ('licenseNotes', models.CharField(blank=True, help_text='license notes', max_length=500)),
                ('furtherInformation', models.CharField(blank=True, help_text='further information', max_length=500)),
                ('alternatives', models.CharField(blank=True, help_text='similar tool(s) that can serve as alternatives', max_length=300)),
                ('provider', models.CharField(blank=True, max_length=300)),
                ('released', models.BooleanField(blank=True, help_text='whether the tool is released or not', null=True)),
                ('releasedPlanned', models.BooleanField(blank=True, help_text='whether publication is planned', null=True)),
                ('yearOfRelease', models.CharField(blank=True, help_text='year of software release (planned or conducted)', max_length=100)),
                ('resources', models.CharField(blank=True, help_text='documentation, literature, git-Repos, etc.', max_length=1000)),
                ('programmingLanguages', models.CharField(blank=True, max_length=500)),
                ('frameworksLibraries', models.CharField(blank=True, max_length=500)),
                ('databaseSystem', models.CharField(blank=True, max_length=500)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.tools')),
                ('specificApplication', models.ManyToManyField(help_text='specific application of the tool in EWB projects (project name + fkz)', to='project_listing.Subproject')),
            ],
            options={
                'verbose_name': 'tools Translation',
                'db_table': 'tools_over_tools_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TargetGroupTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('targetGroup', models.CharField(blank=True, help_text='Which group of people is the tool targeted at?', max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.targetgroup')),
            ],
            options={
                'verbose_name': 'target group Translation',
                'db_table': 'tools_over_targetgroup_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ScaleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('scale', models.CharField(blank=True, help_text='spatial scope of consideration', max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.scale')),
            ],
            options={
                'verbose_name': 'scale Translation',
                'db_table': 'tools_over_scale_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='LifeCyclePhaseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('lifeCyclePhase', models.CharField(blank=True, help_text='Life cycle phase of buildings where the application is used', max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.lifecyclephase')),
            ],
            options={
                'verbose_name': 'life cycle phase Translation',
                'db_table': 'tools_over_lifecyclephase_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FocusTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('focus', models.CharField(help_text='Focus of the Tool', max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.focus')),
            ],
            options={
                'verbose_name': 'focus Translation',
                'db_table': 'tools_over_focus_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ClassificationTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('classification', models.CharField(help_text='Classification Category', max_length=100)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.classification')),
            ],
            options={
                'verbose_name': 'classification Translation',
                'db_table': 'tools_over_classification_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ApplicationAreaTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('applicationArea', models.CharField(blank=True, help_text='application area', max_length=1000)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.applicationarea')),
            ],
            options={
                'verbose_name': 'application area Translation',
                'db_table': 'tools_over_applicationarea_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AccessibilityTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('accessibility', models.CharField(blank=True, help_text='userInterface', max_length=300)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='tools_over.accessibility')),
            ],
            options={
                'verbose_name': 'accessibility Translation',
                'db_table': 'tools_over_accessibility_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
