# Generated by Django 3.2.18 on 2023-09-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(help_text='Classification Category', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Focus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus', models.CharField(help_text='Focus of the Tool', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='name', max_length=150)),
                ('shortDescription', models.CharField(blank=True, help_text='short description', max_length=1000)),
                ('applicationArea', models.CharField(blank=True, help_text='application area', max_length=1000)),
                ('usage', models.CharField(blank=True, help_text='usage', max_length=100)),
                ('lifeCyclePhase', models.CharField(blank=True, help_text='Life cycle phase of buildings where the application is used', max_length=100)),
                ('userInterface', models.CharField(blank=True, help_text='userInterface', max_length=300)),
                ('targetGroup', models.CharField(blank=True, help_text='Which group of people is the tool targeted at?', max_length=300)),
                ('lastUpdate', models.CharField(blank=True, help_text='time (year/month/date) of the last update', max_length=100)),
                ('licence', models.CharField(blank=True, help_text='licence', max_length=200)),
                ('furtherInformation', models.CharField(blank=True, help_text='further information', max_length=500)),
                ('alternatives', models.CharField(blank=True, help_text='similar tool(s) that can serve as alternatives', max_length=300)),
                ('specificApplication', models.CharField(blank=True, help_text='specific application of the tool in EWB projects (project name + fkz)', max_length=500)),
                ('provider', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('classification', models.ManyToManyField(to='tools_over.Classification')),
                ('focus', models.ManyToManyField(to='tools_over.Focus')),
            ],
        ),
    ]
