# Generated by Django 3.2.18 on 2023-07-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_over', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='provider',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
