# Generated by Django 3.2.9 on 2023-05-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_over', '0003_alter_tools_image'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='alternativen',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='anwendungsbereich',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='bezeichnung',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='kategorie',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='konk_anwendung',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='kurzbeschreibung',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='lebenszyklusphase',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='letztes_update',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='lizenz',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='nutzerbewertungen',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='nutzerschnittstelle',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='weitere_informationen',
        # ),
        # migrations.RemoveField(
        #     model_name='tools',
        #     name='zielgruppe',
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='alternatives',
        #     field=models.CharField(blank=True, help_text='similar tool(s) that can serve as alternatives', max_length=300),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='applicationArea',
        #     field=models.CharField(blank=True, help_text='application area', max_length=1000),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='furtherInformation',
        #     field=models.CharField(blank=True, help_text='further information', max_length=500),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='lastUpdate',
        #     field=models.CharField(blank=True, help_text='time (year/month/date) of the last update', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='licence',
        #     field=models.CharField(blank=True, help_text='licence', max_length=200),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='lifeCyclePhase',
        #     field=models.CharField(blank=True, help_text='Life cycle phase of buildings where the application is used', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='name',
        #     field=models.CharField(blank=True, help_text='name', max_length=150),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='shortDescription',
        #     field=models.CharField(default=1, help_text='short description', max_length=1000),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='specificApplication',
        #     field=models.CharField(blank=True, help_text='specific application of the tool in EWB projects (project name + fkz)', max_length=500),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='targetGroup',
        #     field=models.CharField(blank=True, help_text='Which group of people is the tool targeted at?', max_length=300),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='usage',
        #     field=models.CharField(blank=True, help_text='usage', max_length=100),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='userEvaluation',
        #     field=models.DecimalField(blank=True, decimal_places=1, help_text='evaluation of the application by users (range: 1-5 (best), with one decimal place)', max_digits=2, null=True),
        # ),
        # migrations.AddField(
        #     model_name='tools',
        #     name='userInterface',
        #     field=models.CharField(blank=True, help_text='userInterface', max_length=300),
        # ),
    ]
