# Generated by Django 3.2.9 on 2023-05-12 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tools_over', '0004_auto_20230512_1253'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='rating',
        #     name='rating_for',
        # ),
        # migrations.RemoveField(
        #     model_name='rating',
        #     name='rating_from',
        # ),
        # migrations.AddField(
        #     model_name='rating',
        #     name='ratingFor',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratingFor', to='tools_over.tools'),
        # ),
        # migrations.AddField(
        #     model_name='rating',
        #     name='ratingFrom',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ratingFrom', to=settings.AUTH_USER_MODEL),
        # ),
    ]
