# Generated by Django 4.2.1 on 2024-07-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedureItem', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecificProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificProcedureItem', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryShortDescription', models.TextField(blank=True, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('subCategoryShortDescription', models.TextField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('timeRequired', models.CharField(blank=True, max_length=255, null=True)),
                ('groupSize', models.CharField(blank=True, max_length=255, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('advantages', models.TextField(blank=True, null=True)),
                ('disadvantages', models.TextField(blank=True, null=True)),
                ('conductedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('successFactors', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('specificGoals', models.TextField(blank=True, null=True)),
                ('participantObservations', models.CharField(blank=True, max_length=255, null=True)),
                ('persons', models.CharField(blank=True, max_length=255, null=True)),
                ('imageIcon', models.CharField(blank=True, max_length=255, null=True)),
                ('imageIconSelected', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure', models.ManyToManyField(blank=True, null=True, to='user_integration.procedureitem')),
                ('specificProcedure', models.ManyToManyField(blank=True, null=True, to='user_integration.specificprocedureitem')),
            ],
        ),
    ]
