# Generated by Django 4.2.1 on 2024-07-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conArgument', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('literature', models.TextField()),
                ('linkName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proArgument', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcedureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_procedureItem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('categoryShortDescription', models.TextField(blank=True, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('subCategoryShortDescription', models.TextField(blank=True, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('timeRequired', models.TextField(blank=True, null=True)),
                ('groupSize', models.TextField(blank=True, null=True)),
                ('material', models.TextField(blank=True, null=True)),
                ('conductedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('successFactors', models.TextField(blank=True, null=True)),
                ('goals', models.TextField(blank=True, null=True)),
                ('participantObservations', models.CharField(blank=True, max_length=255, null=True)),
                ('persons', models.CharField(blank=True, max_length=255, null=True)),
                ('imageIcon', models.CharField(blank=True, max_length=255, null=True)),
                ('imageIconSelected', models.CharField(blank=True, max_length=255, null=True)),
                ('goodPracticeExample', models.TextField(blank=True, null=True)),
                ('conArguments', models.ManyToManyField(blank=True, null=True, to='user_integration.conargument')),
                ('literature', models.ManyToManyField(blank=True, null=True, to='user_integration.literature')),
                ('proArguments', models.ManyToManyField(blank=True, null=True, to='user_integration.proargument')),
                ('procedure', models.ManyToManyField(blank=True, null=True, to='user_integration.procedureitem')),
            ],
        ),
    ]
