# Generated by Django 4.2.1 on 2024-07-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conArgument', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authors', models.CharField(max_length=500)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('publication_title', models.CharField(max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('publication_location', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProArgument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proArgument', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='advantages',
        ),
        migrations.RemoveField(
            model_name='userengagement',
            name='disadvantages',
        ),
        migrations.AddField(
            model_name='userengagement',
            name='conArguments',
            field=models.ManyToManyField(blank=True, null=True, to='user_integration.conargument'),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='proArguments',
            field=models.ManyToManyField(blank=True, null=True, to='user_integration.proargument'),
        ),
    ]
