# Generated by Django 4.2.1 on 2024-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0002_conargument_literature_proargument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literature',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='publication_location',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='publication_title',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='publication_year',
        ),
        migrations.RemoveField(
            model_name='literature',
            name='publisher',
        ),
        migrations.AddField(
            model_name='literature',
            name='literature',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userengagement',
            name='goodPracticeExample',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userengagement',
            name='literature',
            field=models.ManyToManyField(blank=True, null=True, to='user_integration.literature'),
        ),
    ]
