# Generated by Django 4.2.1 on 2024-07-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0003_remove_literature_authors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='specificProcedure',
        ),
        migrations.AlterField(
            model_name='procedureitem',
            name='procedureItem',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SpecificProcedureItem',
        ),
    ]
