# Generated by Django 4.2.1 on 2024-07-02 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0004_remove_userengagement_specificprocedure_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userengagement',
            name='groupSize',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userengagement',
            name='timeRequired',
            field=models.TextField(blank=True, null=True),
        ),
    ]
