# Generated by Django 4.2.1 on 2024-07-02 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0005_alter_userengagement_groupsize_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedureitem',
            old_name='procedureItem',
            new_name='_procedureItem',
        ),
    ]
