# Generated by Django 4.2.1 on 2024-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0006_rename_procedureitem_procedureitem__procedureitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='linkName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
