# Generated by Django 4.2.1 on 2024-07-09 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_integration', '0007_literature_linkname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userengagement',
            name='specificGoals',
        ),
    ]
