# Generated by Django 3.2.9 on 2022-03-03 15:06

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anschrift',
            fields=[
                ('anschrift_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('plz', models.CharField(max_length=5)),
                ('ort', models.CharField(max_length=50)),
                ('land', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ausfuehrende_stelle',
            fields=[
                ('ausfuehrende_stelle_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('anschrift', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.anschrift')),
            ],
        ),
        migrations.CreateModel(
            name='Enargus',
            fields=[
                ('enargus_id', models.AutoField(primary_key=True, serialize=False)),
                ('laufzeitbeginn', models.DateField(blank=True)),
                ('laufzeitende', models.DateField(blank=True)),
                ('thema', models.CharField(blank=True, max_length=500)),
                ('verbundbezeichnung', models.CharField(blank=True, max_length=200)),
                ('datenbank', models.CharField(default=sqlalchemy.sql.expression.null, help_text='Datenbank Information/Enargus Intern', max_length=15)),
                ('kurzbeschreibung_de', models.TextField(default=sqlalchemy.sql.expression.null, help_text='Deutsche Kurzbeschreibung')),
                ('kurzbeschreibung_en', models.TextField(default=sqlalchemy.sql.expression.null, help_text='Englische Kurzbeschreibung')),
                ('foerdersumme', models.DecimalField(blank=True, decimal_places=2, help_text='Foerdersumme in EUR', max_digits=10, null=True)),
                ('ausfuehrende_stelle', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.ausfuehrende_stelle')),
            ],
        ),
        migrations.CreateModel(
            name='Forschung',
            fields=[
                ('forschung_id', models.AutoField(help_text='Auto.generiert ID', primary_key=True, serialize=False)),
                ('bundesministerium', models.CharField(blank=True, help_text='Akronym des Bundesministeriums', max_length=10)),
                ('projekttraeger', models.CharField(blank=True, help_text='Name des Projektraegers', max_length=50)),
                ('forschungsprogramm', models.CharField(blank=True, help_text='Name des Forschungsprogramms', max_length=50)),
                ('foerderprogramm', models.CharField(blank=True, help_text='Name des Forderprogramms', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fragebogen_21',
            fields=[
                ('Fragebogen_21', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Leistung_sys',
            fields=[
                ('leistungsplansystematik_nr', models.CharField(help_text='Leistungsplansystematiknummer', max_length=6, primary_key=True, serialize=False)),
                ('leistungsplansystematik_text', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Modulen_zuordnung_ptj',
            fields=[
                ('mod_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('priority_1', models.CharField(help_text='Projektzuordnung mit der Prioritat 1, ag: ausgelaufen', max_length=2)),
                ('priority_2', models.CharField(help_text='Projektzuordnung mit der Prioritat 2, ag: ausgelaufen', max_length=2)),
                ('priority_3', models.CharField(help_text='Projektzuordnung mit der Prioritat 3, ag: ausgelaufen', max_length=2)),
                ('priority_4', models.CharField(blank=True, help_text='Projektzuordnung mit der Prioritat 4, ag: ausgelaufen', max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name der Person', max_length=100)),
                ('vorname', models.CharField(help_text='Vorname der Person', max_length=50)),
                ('titel', models.CharField(help_text='Titel der Person', max_length=50)),
                ('email', models.EmailField(help_text='Email_Adresse der Person', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Schlagwort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schlagwort_id', models.CharField(help_text='Name des Schlagwortes', max_length=200)),
                ('schlagwort_definition', models.CharField(help_text='Definition des Schlagwortes', max_length=1500)),
                ('literatur', models.CharField(help_text='Literaturquellen zum Schlagwort', max_length=1500)),
            ],
        ),
        migrations.CreateModel(
            name='Schlagwortregister_erstsichtung',
            fields=[
                ('schlagwortregister_erstsichtung_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('schlagwort_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_1', to='project_listing.schlagwort')),
                ('schlagwort_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_2', to='project_listing.schlagwort')),
                ('schlagwort_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_3', to='project_listing.schlagwort')),
                ('schlagwort_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_4', to='project_listing.schlagwort')),
                ('schlagwort_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_5', to='project_listing.schlagwort')),
                ('schlagwort_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_6', to='project_listing.schlagwort')),
                ('schlagwort_7', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schlagwort_7', to='project_listing.schlagwort')),
            ],
        ),
        migrations.CreateModel(
            name='Zuwendungsempfaenger',
            fields=[
                ('zuwendungsempfaenger_id', models.AutoField(help_text='auto generiert ID', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('anschrift', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.anschrift')),
            ],
        ),
        migrations.CreateModel(
            name='Teilprojekt',
            fields=[
                ('fkz', models.CharField(help_text='Förderkennzeichen', max_length=10, primary_key=True, serialize=False)),
                ('enargus_daten', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_listing.enargus')),
                ('fragebogen_21', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.fragebogen_21')),
                ('schlagwoerter_erstsichtung', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.schlagwortregister_erstsichtung')),
                ('zuordnung', models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.modulen_zuordnung_ptj')),
            ],
        ),
        migrations.AddField(
            model_name='enargus',
            name='forschung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.forschung'),
        ),
        migrations.AddField(
            model_name='enargus',
            name='leistungsplan_systematik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.leistung_sys'),
        ),
        migrations.AddField(
            model_name='enargus',
            name='projektleiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.person'),
        ),
        migrations.AddField(
            model_name='enargus',
            name='zuwendsempfanger',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='project_listing.zuwendungsempfaenger'),
        ),
    ]
