# Generated by Django 3.2.9 on 2021-12-20 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enargus',
            fields=[
                ('enargus_id', models.AutoField(primary_key=True, serialize=False)),
                ('laufzeitbeginn', models.DateTimeField(blank=True)),
                ('laufzeitende', models.DateTimeField(blank=True)),
                ('thema', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Teilprojekt',
            fields=[
                ('fkz', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('enargus_daten', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_listing.enargus')),
            ],
        ),
    ]
