# Generated by Django 3.2.9 on 2021-12-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enargus',
            name='verbundbezeichnung',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
