# Generated by Django 3.2.9 on 2023-06-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randdplanningcategory',
            old_name='rAndDPlanningCategory_id',
            new_name='rAndDPlanningCategoryNumber',
        ),
    ]
