# Generated by Django 3.2.9 on 2022-03-03 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(blank=True, help_text='Name der Anwendung', max_length=150)),
                ('kurzbeschreibung', models.CharField(help_text='Kurzbeschreibung der Anwendung', max_length=1000)),
                ('anwendungsbereich', models.CharField(blank=True, help_text='Anwendungsbereich der Anwendung', max_length=1000)),
                ('kategorie', models.CharField(blank=True, help_text='Kategorie in der die Anwendung eingeordnet werden kann', max_length=100)),
                ('lebenszyklusphase', models.CharField(blank=True, help_text='Lebenszyklusphase von Gebäuden                                         in der die Anwendung genutzt wird', max_length=100)),
                ('nutzerschnittstelle', models.CharField(blank=True, help_text='Nutzerschnittstelle                                            (wie wird die Anwendung vom Nutzer genutzt)', max_length=300)),
                ('zielgruppe', models.CharField(blank=True, help_text='Zielgruppe der Anwendung', max_length=300)),
                ('letztes_update', models.CharField(blank=True, help_text='letztes Update der Anwendung', max_length=100)),
                ('lizenz', models.CharField(blank=True, help_text='Lizenz der Anwendung', max_length=200)),
                ('weitere_informationen', models.CharField(blank=True, help_text='weitere Informationen zur Anwendung', max_length=500)),
                ('alternativen', models.CharField(blank=True, help_text='Alternativen zu der jeweiligen Anwendung', max_length=300)),
                ('konk_anwendung', models.CharField(blank=True, help_text='konkrete Anwendung in EWB Projekten', max_length=500)),
                ('nutzerbewertungen', models.DecimalField(blank=True, decimal_places=1, help_text='Bewertung der Anwendung durch Nutzende                                             (geplant max. 10 mit einer Kommastelle, max. 10.0)', max_digits=3, null=True)),
            ],
        ),
    ]
