# Generated by Django 3.2.9 on 2023-06-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0002_rename_randdplanningcategory_id_randdplanningcategory_randdplanningcategorynumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enargus',
            old_name='projektleiter',
            new_name='projectLead',
        ),
    ]
