# Generated by Django 3.2.9 on 2022-03-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0002_tools'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tools',
        ),
    ]
