# Generated by Django 3.2.9 on 2022-07-14 09:57

from django.db import migrations, models
import django.db.models.deletion
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    dependencies = [
        ('schlagwoerter', '0001_initial'),
        ('project_listing', '0003_delete_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_1',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_2',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_3',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_4',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_5',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_6',
        ),
        migrations.RemoveField(
            model_name='schlagwortregister_erstsichtung',
            name='schlagwort_7',
        ),
        migrations.RemoveField(
            model_name='teilprojekt',
            name='schlagwoerter_erstsichtung',
        ),
        migrations.AddField(
            model_name='teilprojekt',
            name='schlagwortregister_erstsichtung',
            field=models.ForeignKey(blank=True, null=sqlalchemy.sql.expression.true, on_delete=django.db.models.deletion.SET_NULL, to='schlagwoerter.schlagwortregister_erstsichtung'),
            preserve_default=sqlalchemy.sql.expression.true,
        ),
        migrations.DeleteModel(
            name='Schlagwort',
        ),
        migrations.DeleteModel(
            name='Schlagwortregister_erstsichtung',
        ),
    ]
