# Generated by Django 3.2.9 on 2021-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0003_alter_enargus_laufzeitbeginn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enargus',
            name='laufzeitende',
            field=models.DateField(blank=True),
        ),
    ]
