# Generated by Django 3.2.9 on 2021-12-20 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0004_alter_enargus_laufzeitende'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forschung',
            fields=[
                ('forschung_id', models.AutoField(primary_key=True, serialize=False)),
                ('bundesministerium', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='enargus',
            name='forschung',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_listing.forschung'),
        ),
    ]
