# Generated by Django 3.2.9 on 2021-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0005_auto_20211220_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='teilprojekt',
            name='foerdersumme',
            field=models.IntegerField(help_text='Foerdersumme in EUR', null=True),
        ),
    ]
