# Generated by Django 3.2.9 on 2021-12-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0006_teilprojekt_foerdersumme'),
    ]

    operations = [
        migrations.AddField(
            model_name='forschung',
            name='foerderprogramm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forschung',
            name='forschungsprogramm',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='forschung',
            name='projekttraeger',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
