# Generated by Django 4.2.1 on 2024-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Weatherdata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_service",
                    models.CharField(
                        blank=True,
                        help_text="Name der Anwendung",
                        max_length=150,
                    ),
                ),
                (
                    "data_service_de",
                    models.CharField(
                        blank=True,
                        help_text="Name der Anwendung",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "data_service_en",
                    models.CharField(
                        blank=True,
                        help_text="Name der Anwendung",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "short_description",
                    models.CharField(
                        blank=True,
                        help_text="Kurzbeschreibung des DatenService",
                        max_length=1000,
                    ),
                ),
                (
                    "short_description_de",
                    models.CharField(
                        blank=True,
                        help_text="Kurzbeschreibung des DatenService",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "short_description_en",
                    models.CharField(
                        blank=True,
                        help_text="Kurzbeschreibung des DatenService",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="Provider des DatenService",
                        max_length=150,
                    ),
                ),
                (
                    "provider_de",
                    models.CharField(
                        blank=True,
                        help_text="Provider des DatenService",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "provider_en",
                    models.CharField(
                        blank=True,
                        help_text="Provider des DatenService",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "further_information",
                    models.CharField(
                        blank=True,
                        help_text="weitere Informationen zum DatenService",
                        max_length=500,
                    ),
                ),
                (
                    "further_information_de",
                    models.CharField(
                        blank=True,
                        help_text="weitere Informationen zum DatenService",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "further_information_en",
                    models.CharField(
                        blank=True,
                        help_text="weitere Informationen zum DatenService",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "data_url",
                    models.CharField(
                        blank=True,
                        help_text="Url zum Datensatz",
                        max_length=300,
                    ),
                ),
                (
                    "logo_url",
                    models.CharField(
                        blank=True, help_text="Url zum Logo", max_length=300
                    ),
                ),
                (
                    "applications",
                    models.CharField(
                        blank=True,
                        help_text="konkrete Anwendung der Datensätze bzw. der Werkzeuge",
                        max_length=500,
                    ),
                ),
                (
                    "applications_de",
                    models.CharField(
                        blank=True,
                        help_text="konkrete Anwendung der Datensätze bzw. der Werkzeuge",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "applications_en",
                    models.CharField(
                        blank=True,
                        help_text="konkrete Anwendung der Datensätze bzw. der Werkzeuge",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "last_update",
                    models.CharField(
                        blank=True,
                        help_text="letztes Update des DatenServices",
                        max_length=100,
                    ),
                ),
                (
                    "last_update_de",
                    models.CharField(
                        blank=True,
                        help_text="letztes Update des DatenServices",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "last_update_en",
                    models.CharField(
                        blank=True,
                        help_text="letztes Update des DatenServices",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "license",
                    models.CharField(
                        blank=True,
                        help_text="Lizenz des DatenServices",
                        max_length=200,
                    ),
                ),
                (
                    "license_de",
                    models.CharField(
                        blank=True,
                        help_text="Lizenz des DatenServices",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "license_en",
                    models.CharField(
                        blank=True,
                        help_text="Lizenz des DatenServices",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Kategorie des DatenServices (Datensatz, Anwendung, ...)",
                        max_length=150,
                    ),
                ),
                (
                    "category_de",
                    models.CharField(
                        blank=True,
                        help_text="Kategorie des DatenServices (Datensatz, Anwendung, ...)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "category_en",
                    models.CharField(
                        blank=True,
                        help_text="Kategorie des DatenServices (Datensatz, Anwendung, ...)",
                        max_length=150,
                        null=True,
                    ),
                ),
                (
                    "long_description",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibung des DatenService",
                        max_length=10000,
                    ),
                ),
                (
                    "long_description_de",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibung des DatenService",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "long_description_en",
                    models.CharField(
                        blank=True,
                        help_text="Beschreibung des DatenService",
                        max_length=10000,
                        null=True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
            ],
        ),
    ]
