# Generated by Django 4.2.1 on 2024-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive_environmental_impact', '0003_environmentalimpact_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalimpact',
            name='consortium',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='consortium_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='consortium_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='evaluation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='evaluation_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='evaluation_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='goals_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='goals_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='implementation_in_the_project',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='implementation_in_the_project_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='implementation_in_the_project_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='partner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='partner_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='partner_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='problem_statement_and_problem_goals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='problem_statement_and_problem_goals_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='problem_statement_and_problem_goals_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='relevance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='relevance_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='relevance_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='strategies',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='strategies_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='strategies_en',
            field=models.TextField(blank=True, null=True),
        ),
    ]
