# Generated by Django 5.0.9 on 2024-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        ("project_listing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalImpact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("category_de", models.CharField(max_length=255, null=True)),
                ("category_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField()),
                ("description_de", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("name_digital_application", models.CharField(max_length=255)),
                (
                    "name_digital_application_de",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "name_digital_application_en",
                    models.CharField(max_length=255, null=True),
                ),
                ("project_name", models.CharField(max_length=255)),
                (
                    "project_name_de",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "project_name_en",
                    models.CharField(max_length=255, null=True),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "partner",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "partner_de",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "partner_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("project_website", models.URLField(blank=True, null=True)),
                ("consortium", models.TextField(blank=True, null=True)),
                ("consortium_de", models.TextField(blank=True, null=True)),
                ("consortium_en", models.TextField(blank=True, null=True)),
                ("further", models.TextField(blank=True, null=True)),
                ("further_de", models.TextField(blank=True, null=True)),
                ("further_en", models.TextField(blank=True, null=True)),
                (
                    "digitalApplications",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "digitalApplications_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "digitalApplications_en",
                    models.TextField(blank=True, null=True),
                ),
                ("goals", models.TextField(blank=True, null=True)),
                ("goals_de", models.TextField(blank=True, null=True)),
                ("goals_en", models.TextField(blank=True, null=True)),
                ("strategies", models.TextField(blank=True, null=True)),
                ("strategies_de", models.TextField(blank=True, null=True)),
                ("strategies_en", models.TextField(blank=True, null=True)),
                ("relevance", models.TextField(blank=True, null=True)),
                ("relevance_de", models.TextField(blank=True, null=True)),
                ("relevance_en", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "problem_statement_and_problem_goals",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "problem_statement_and_problem_goals_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "problem_statement_and_problem_goals_en",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "implementation_in_the_project",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "implementation_in_the_project_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "implementation_in_the_project_en",
                    models.TextField(blank=True, null=True),
                ),
                ("evaluation", models.TextField(blank=True, null=True)),
                ("evaluation_de", models.TextField(blank=True, null=True)),
                ("evaluation_en", models.TextField(blank=True, null=True)),
                (
                    "funding_label",
                    models.ManyToManyField(
                        blank=True, null=True, to="project_listing.subproject"
                    ),
                ),
                (
                    "literature",
                    models.ManyToManyField(
                        blank=True, null=True, to="common.literature"
                    ),
                ),
            ],
        ),
    ]
