# Generated by Django 4.2.1 on 2024-08-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_listing', '0001_initial'),
        ('positive_environmental_impact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalimpact',
            name='digitalApplications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='digitalApplications_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='digitalApplications_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='environmentalimpact',
            name='funding_label',
        ),
        migrations.AlterField(
            model_name='environmentalimpact',
            name='project_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='environmentalimpact',
            name='funding_label',
            field=models.ManyToManyField(blank=True, null=True, to='project_listing.subproject'),
        ),
    ]
