# Generated by Django 4.2.1 on 2024-08-06 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positive_environmental_impact', '0002_alter_environmentalimpact_digitalapplications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentalimpact',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
