# Generated by Django 4.2.1 on 2024-04-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UseCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=25, unique=True)),
                ('useCase', models.CharField(max_length=50)),
                ('sriLevel', models.CharField(max_length=255, verbose_name='SRI-Zuordnung')),
                ('levelOfAction', models.CharField(max_length=100)),
                ('degreeOfDetail', models.CharField(max_length=100)),
                ('perspective', models.CharField(max_length=255)),
                ('idPerspectiveforDetail', models.PositiveIntegerField()),
                ('effectEvaluation', models.CharField(choices=[('+', 'Positive'), ('-', 'Negative'), ('o', 'Neutrale')], max_length=1)),
                ('effectName', models.CharField(max_length=255)),
                ('effectDescription', models.TextField()),
                ('furtherInformation', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
            ],
        ),
    ]
