# Generated by Django 4.2.1 on 2024-04-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools_over', '0001_initial'),
        ('use_cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='perspective',
        ),
        migrations.AddField(
            model_name='usecase',
            name='focus',
            field=models.ManyToManyField(to='tools_over.focus'),
        ),
    ]
