# Generated by Django 4.2.1 on 2024-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_cases', '0002_remove_usecase_perspective_usecase_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='item_code',
            field=models.CharField(max_length=25),
        ),
    ]
