# Generated by Django 4.2.1 on 2024-04-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('use_cases', '0003_alter_usecase_item_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='icon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
